### PR TITLE
CZML Interval Edge Case Error

### LINKED ISSUE #9097: Error removing CZML datasource when start and end time in clock interval are the same
It seems to only throw an error when using the result from the promise.

Code:
```
var viewer = new Cesium.Viewer("cesiumContainer");
async function doIt() {
  var czml = [
    {
      "id":"document",
      "version":"1.0",
      "clock":
        {
          "interval":"2020-01-01T00:00:00+00:00/2020-01-01T00:00:00+00:00",
          "currentTime":"2020-01-01T00:00:00+00:00",
          "multiplier":30,
          "range":"CLAMPED",
          "step":"SYSTEM_CLOCK_MULTIPLIER"
        }
    }
  ];
  var dataSourcePromise = Cesium.CzmlDataSource.load(czml);
  viewer.dataSources.add(dataSourcePromise);
  const dataSource = await dataSourcePromise;
  viewer.dataSources.remove(dataSource);
}


doIt();
```

Error:
```
Uncaught (in promise) TypeError: this._dataSourceChangedListeners[id] is not a function
    at Viewer._onDataSourceRemoved (VM332 Cesium.js:304106)
    at Event.raiseEvent (VM332 Cesium.js:14039)
    at DataSourceCollection.remove (VM332 Cesium.js:195798)
    at doIt (<anonymous>:24:22)
```

Sandcastle example:
https://sandcastle.cesium.com/#c=jVJdT9swFP0rVp5SjTkpe2tDNRT6UC0V1VqQ0IyQcS5g4diVP1KVaf99jh3WQEFaYjnxPfecY/velmrUctiBRmdIwg6VYLhr8HWIpSRhYV0qaSmXoEkymhJJzV4y9OAks1xJVKuFTUfoN5EItV6QvTTCy/3q1iiGu4ckvCbJhCS1Yq4BaUlycsAkbSCg10p41LwBW9DGOwV8jPM3GBOKPXdIHxk49q7Sgm6pCOzT/DT/mo/92OT5JIwvYc4+RQZuvaPT2m9/w/sd/z+zccLyreDdRU6+5e9QTeVjVCyr8+VqfnHENxa2IWF9s97Ml3dldVn+uFteVZvFqlrMf5LkkP8n/obP7fS1NjW1dK2cZrDSquEGfKH6mpe+bBf/YCwUrdOulKNIDh2BD3yDaV2nR3oxmylp7MDMu9Ad5fbY/zNxDY1qYaDfCfvDdG9suGlykhTG7gXMXk/9nTdbpS1yWqQYZxaaraAWTHbv2DNYzIyJ+0OoyIbUouYt4vXZBw2PmKDGeOTBCbHmL75CsyLz+UfU7sa4fLz03Srovkt7Gs+qGMQYF5lffsy0Sol7qgfKMeMv

Browser:
Chrome

Operating System:
macOs

Workaround / prevention:
Don't allow clock interval have the same start/end time.

### PR DESCRIPTION
**Pull request by srothst1**
Fixes #9097 

Resolves an error related to removing a CZML datasource when the clock interval has a duration of zero.

The [ISO documentation](https://en.wikipedia.org/wiki/ISO_8601) conclusively says that a duration can be zero. The documentation also indicates that the amount of intervening time on a time interval is expressed by a duration. Thus, the original suggestion in #9097 to not permit CZML data with clock intervals of duration 0 does not seem to meet ISO standards.

The methods `removeAll()` and `remove()` in DataSourceCollection.js both cause the same problem outlined in the issue. When removing a dataSource with an intervening time of 0, the error stems from the line `this._dataSourceRemoved.raiseEvent(this, dataSource);` in both methods. I looked at the method `raiseEvent` in Event.js but was not able to find the cause of the error. Assistance on this matter would be appreciated.

[This sandcastle demo](http://localhost:8080/Apps/Sandcastle/index.html#c=lVRtb9owEP4rVj4lWmsH9g0oWhWQhgYqGqzStEyVca7UqmMjvwTBtP8+x6HlfdMS58X3PHeP73xJRTWqOKxBozskYY0yMNyV+DHY4jxiYZ4paSmXoPMo6eaSmo1k6NlJZrmSqFAjGyfoVy4RqnxAti2FD/ejnqPGXB95xIs86uRRoZgrQdo8utljkpYQ0EclPGqOwAq08UoBb+H0CGNCsdca2VkOFHeq0oKuqAje7bSd3qYtP+Zp2gnjQ7iTq4hXQ4RsQSv0HupAgJD/kfDmth8XJaSSt0cy+yRO9AqnqQ0FQR2f4TQd/GORvkxOa1/zOd+V+W/pHnuWTli+Erze/c7H9ATVVC6biNn4fjIdDs78jYVVIMy+z+bDyVM2fsi+PE2+jeej6Xg0/JpHe/7v5jU8fnbfGqqgls6U0wymWpXcgO+uXaNmvtcG7zAWihZx3X9J4xzaGO/9DaZFEZ/Fa9hMSWMPxLwKXVNuz/UDnZDPoAFRfxlVAlq4pelcUdVQqgoOhJNdiKvceyFO6L4o9dl8bZhRy15iv8Z+WLcSdfLLGJKkG91EPWM3Avpvhf3Ey5XSFjktYoyJhXIlqAVDFo69gsXMmGZBCPXIoWuv4BXixd2FHwFighrjkWcnxIxvfRP0e8Tzz1zrTeFy+eC/YkE3Ne2l1R83Roxxj/jpZU+rlFhQfRL5Dw) shows the different test cases as well as the errors.

@ebogo1 
@lilleyse

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @srothst1!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/removing-CZML-datasource-edge-case/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by srothst1** [comment]
Given the console error: `TypeError: this._dataSourceChangedListeners[id] is not a function`, I removed the line `this._dataSourceChangedListeners[id]()` from Viewer.js. This appears to have fixed both errors shown in my [sandcastle demo](http://localhost:8080/Apps/Sandcastle/index.html#c=lVRtb9owEP4rVj4lWmsH9g0oWhWQhgYqGqzStEyVca7UqmMjvwTBtP8+x6HlfdMS58X3PHeP73xJRTWqOKxBozskYY0yMNyV+DHY4jxiYZ4paSmXoPMo6eaSmo1k6NlJZrmSqFAjGyfoVy4RqnxAti2FD/ejnqPGXB95xIs86uRRoZgrQdo8utljkpYQ0EclPGqOwAq08UoBb+H0CGNCsdca2VkOFHeq0oKuqAje7bSd3qYtP+Zp2gnjQ7iTq4hXQ4RsQSv0HupAgJD/kfDmth8XJaSSt0cy+yRO9AqnqQ0FQR2f4TQd/GORvkxOa1/zOd+V+W/pHnuWTli+Erze/c7H9ATVVC6biNn4fjIdDs78jYVVIMy+z+bDyVM2fsi+PE2+jeej6Xg0/JpHe/7v5jU8fnbfGqqgls6U0wymWpXcgO+uXaNmvtcG7zAWihZx3X9J4xzaGO/9DaZFEZ/Fa9hMSWMPxLwKXVNuz/UDnZDPoAFRfxlVAlq4pelcUdVQqgoOhJNdiKvceyFO6L4o9dl8bZhRy15iv8Z+WLcSdfLLGJKkG91EPWM3Avpvhf3Ey5XSFjktYoyJhXIlqAVDFo69gsXMmGZBCPXIoWuv4BXixd2FHwFighrjkWcnxIxvfRP0e8Tzz1zrTeFy+eC/YkE3Ne2l1R83Roxxj/jpZU+rlFhQfRL5Dw).

**Comment by lilleyse** [comment]
Removing `this._dataSourceChangedListeners[id]();` is simply hiding the problem and mostly likely introducing a bug in the process.

See why the listener never got added in the first place. Step through `_onDataSourceAdded` and you'll notice that `this._dataSourceChangedListeners[id] = removalFunc;` never gets hit because of an error thrown in one of the preceding calls.

**Comment by srothst1** [comment]
@lilleyse It seems like `this.clockTrackedDataSource = dataSource;` is causing the error, however, I am not seeing exactly what it is on the console in Sandcastle.

One quick fix would be to call `this._dataSourceChangedListeners[id] = removalFunc;` before updating `this.clockTrackedDataSource`. This would ensure that `this._dataSourceChangedListeners[id]();` in `Viewer.prototype._onDataSourceRemoved` has a valid value.

**Comment by srothst1** [comment]
@lilleyse I believe the simplest solution is to allow for the `startTime` and the `stopTime` to be equivalent in `Timeline.prototype.zoomTo`. This prevents errors from occurring when an empty interval is added and `viewer.dataSources.remove(dataSource);` or `viewer.dataSources.removeAll(dataSource);` is called. It also does not seem to negatively impact any other functions. 

After updating `Timeline.prototype.zoomTo`, the empty interval
`"interval":"2020-01-01T00:00:00+00:00/2020-01-01T00:00:00+00:00"`

yields 

image

which is both intuitive and user-friendly functionality.

**Comment by lilleyse** [comment]
Now that I've stepped through the timeline code a little bit I'm pretty sure the `lessThanOrEquals` check is there for good reason.

There's a divide by zero [here](https://github.com/CesiumGS/cesium/blob/5540c3006ce5dd0fa5de83410ae0b16b31dd56c4/Source/Widgets/Timeline/Timeline.js#L421) when `this._timeBarSecondsSpan` is zero. The timeline code seems to handle the resulting NaN gracefully because it clamps the duration to a minimum duration of 0.01 seconds, but some of the generated css code still uses variables that are NaN. Maybe those NaN's are handled gracefully elsewhere.

Rather than relying on this behavior I think a better solution is to clamp `this._timeBarSecondsSpan` to the minimum/maximum duration right as it's set in `zoomTo`. Either that or fix this in `Viewer` `trackDataSourceClock` by passing in a stop time that's slightly larger than the start time.

Open to other suggestions as this isn't a system I'm super familiar with.

**Comment by srothst1** [comment]
@lilleyse From what I can tell, the timeline code and the generated CSS code handle `NaN` gracefully. 

Of your two proposed solutions, I think the second is slightly more intuitive. I implemented it in the most recent commit. When `dataSourceClock.startTime` is equivalent to `dataSourceClock.stopTime`, I set `dataSourceClock.stopTime` to 5 seconds past `dataSourceClock.startTime`. My choice of 5 seconds is somewhat arbitrary - is there a more appropriate time window that I should use?

Curious to hear your overall thoughts!

**Comment by lilleyse** [comment]
>  choice of 5 seconds is somewhat arbitrary - is there a more appropriate time window that I should use?

Ultimately it is arbitrary but `CesiumMath.EPSILON2` (0.01) seems like an ok choice because it matches the timelines own internal minimum and is close-ish to zero.

File: Source/Widgets/Viewer/Viewer.js [hunk 1]
```diff
@@ -141,6 +142,15 @@ function trackDataSourceClock(timeline, clock, dataSource) {
...
       if (defined(timeline)) {
+        if (
+          JulianDate.equals(dataSourceClock.startTime, dataSourceClock.stopTime)
+        ) {
+          JulianDate.addSeconds(
+            dataSourceClock.startTime,
+            5,
+            dataSourceClock.stopTime
+          );
+        }
```
Comment (lilleyse) [inline Source/Widgets/Viewer/Viewer.js:153]: It feels a little wrong to modify the data sources's `stopTime` when it's really just the timeline that needs special behavior. This is a good place to use a scratch variable.

```js
var scratchStopTime = new JulianDate();

function trackDataSourceClock(timeline, clock, dataSource) {
  if (defined(dataSource)) {
    var dataSourceClock = dataSource.clock;
    if (defined(dataSourceClock)) {
      dataSourceClock.getValue(clock);
      if (defined(timeline)) {
        var startTime = dataSourceClock.startTime;
        var stopTime = dataSourceClock.stopTime;
        if (JulianDate.equals(startTime, stopTime)) {
          stopTime = JulianDate.addSeconds(
            dataSourceClock.startTime,
            CesiumMath.EPSILON2,
            scratchStopTime
          );
        }
        timeline.updateFromClock();
        timeline.zoomTo(startTime, stopTime);
      }
    }
  }
}
```

Comment (lilleyse) [inline Source/Widgets/Viewer/Viewer.js:153]: Add a comment in the code explaining what the fix is doing and why it's needed. This will help future readers understand what's going on.

**Comment by srothst1** [comment]
@lilleyse I just updated `Viewer.js`. Specifically, I 
1. used a scratch variable instead of modifying  `dataSourceClock.stopTime`
2. Added a comment explaining the new `if` statement.
Let me know how this looks.

**Comment by lilleyse** [comment]
Thanks @srothst1, I pushed a couple small commits (one was a small mistake in my example code above). Once CI passes this will be ready to merge.
