### PR TITLE
Fix glTF animations in tileset

### LINKED ISSUE #8962: Support glTF animations in 3D Tiles payloads
Hi, is there somewhere a sample/documention of playing glTF animation from b3dm tile(s) in Cesium? Is it supported? I see my tiles are rendered in Cesium but the animation is not playing :-(

### PR DESCRIPTION
**Pull request by ErixenCruz**
Fixes #8962 
Fixed issue where tileset was not playing glTF animations.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ErixenCruz!
* :heavy_check_mark: Signed CLA found.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by lilleyse** [comment]
@ErixenCruz here are some tilesets to test with.

[BatchedAnimated.zip](https://github.com/CesiumGS/cesium/files/4821547/BatchedAnimated.zip) - place in `Specs/Data/Cesium3DTiles/Batched/` 
[InstancedAnimated.zip](https://github.com/CesiumGS/cesium/files/4821548/InstancedAnimated.zip) - place in `Specs/Data/Cesium3DTiles/Instanced/`

[Local sandcastle for viewing these](http://localhost:8080/Apps/Sandcastle/index.html#c=jZFNSwMxEIb/StjTCiVBvLXbom0vguChtadc0mTsRvOx5GNLK/53k90trVrBEJhk5p0nM5OWOdRK2INDU2RgjxbgZdR40/lKWvDuvrAmMGnA0WKEPqhByNc2KvFgpGYBxii4CCNqPm8m1FDTJmqQCjyE79je3C3XfbDsUNGpMaIFxqTfqwa4J0sWGPmmJ4/GB2Y4iPNpKECQ4Tn85q1JRWYuIf8mz1ngdaIM9g/qub9uOthzMIAbJ7UMsgWPmRDlkJKFg+xorV7bywA1J7CAbdytart/cSqNKo9xciU6t9EIaXYbq6KGk7AYFZUPBwWz3G5e91I31oU80jL1G0A3KjXiyTby9wTk3uf3s7Qil6mVkC2SYnrlwxFXzPsUeY1KreQRaDGrSNL/SlWW5SKfW3CKHbKsvp099U6McUXS9XpmsFZtmftB/gI)

Add two tests to `Cesium3DTilesetSpec`, one for the batched tileset and another for the instanced tileset. Since the tests will be very similar you can factor out most of the work into a local function that both tests will call. The test should
1. Load the tileset - see the `"renders tileset"` test for an example
2. Once the tileset is loaded, render the scene at a specific time - see `"renders with imageBaseLightingFactor"` for an example.
3. Grab the first command in `frameState`'s command list (see `"adds stencil clear command first when unresolved"`) and save it's model matrix (you can use `Matrix4.clone`)
4. Render the scene again 0.5 seconds later.
5. Grab the first command again and compare the model matrix with the saved model matrix. You can use `expect(matrixA).not.toEqual(matrixB)` for this.

Let me know how this goes!

**Comment by ErixenCruz** [comment]
@lilleyse How's that?

File: Source/Scene/ModelInstanceCollection.js [hunk 1]
```diff
@@ -997,9 +998,15 @@ ModelInstanceCollection.prototype.update = function (frameState) {
...
-      that._readyPromise.reject(error);
+    this._model.readyPromise.then(function (model) {
+      model.activeAnimations
+        .addAll({
+          loop: ModelAnimationLoop.REPEAT,
+        })
+        .otherwise(function (error) {
+          that._state = LoadState.FAILED;
+          that._readyPromise.reject(error);
+        });
```
Comment (lilleyse) [inline Source/Scene/ModelInstanceCollection.js:1009]: The `otherwise` should be chained after `.then` rather than after `.addAll`. This `.then`/`.otherwise` chain allows the promise to be handled correctly whether the promise is resolved or rejected.

Chaining it after `addAll` wouldn't end up catching an error since `addAll` does not return a promise. My mistake for missing this earlier, I think I got lost in the indendation.

```suggestion
    this._model.readyPromise
      .then(function (model) {
        model.activeAnimations.addAll({
          loop: ModelAnimationLoop.REPEAT,
        });
      })
      .otherwise(function (error) {
        that._state = LoadState.FAILED;
        that._readyPromise.reject(error);
      });
```

Comment (lilleyse) [reply Source/Scene/ModelInstanceCollection.js:1009]: Despite this code suggestion, I've been thinking more about the overall design here and think it makes sense to bring the functionality to `Instanced3DModel3DTileContent` instead. I didn't noticed until reviewing that `ModelInstanceCollection` already has an `activeAnimations` getter and it's the caller's responsibility whether to add animations or not.

So the change will be something like this: in `Instanced3DModel3DTileContent`, after `ModelInstanceCollection` is created, add the animations when the collection is ready. It'll look just like the `Batched3DModel3DTileContent` code in this PR except that model will be a model instance collection.

File: Specs/Scene/Cesium3DTilesetSpec.js [hunk 2]
```diff
@@ -637,6 +641,35 @@ describe(
       });
     });
 
+    function checkAnimation(url) {
```
Comment (lilleyse) [inline Specs/Scene/Cesium3DTilesetSpec.js:644]: The tests looks great

**Comment by lilleyse** [comment]
Looks like CI has some test failures. https://github.com/CesiumGS/cesium/pull/8983#discussion_r445907365 seems to be the cause. Once that's addressed there shouldn't be any issues.

**Comment by ErixenCruz** [comment]
Even after the fixes, some tests still fail. In particular, `Scene/Instanced3DModel3DTileContent rejects readyPromise on error` times out. Investigating.

**Comment by ErixenCruz** [comment]
@lilleyse Tests pass! Like I mentioned, I have to rely on TravisCI for testing. Unreliable to run on my browser.

**Comment by lilleyse** [comment]
Local tests work for me. There's some test failures on Mac/Chrome but none introduced in this branch.

Thanks @ErixenCruz
