### PR TITLE
Document additional limitations of 3D Tiles classification

### LINKED ISSUE #11341: Using 3D Tiles for classification doesn't seem to work
As an experiment, I threw together this simple Sandcastle to attempt to classify Google buildings with OSM data. [Link](https://sandcastle.cesium.com/#c=fVRbb9owFP4rR2gPqURNQhJCNlqto9VWiapoZXuK1JrkFKw5NrINjFX97zu5sNHrixWf63e+fMe5VtbBRuAWDZyAwi2M0Yp1yX7WNi/r5PV9rJXjQqHJOl14yBSAEyVKsnyEey4tdisbV6LkTmh1aLQ5KrzSBU5F/gvNoWvOLU74Ds1z1+PRp0xlqteD2RJhIfUcodBoQWlHKLEAp6GyCbuSVKDo1sFWqBzBUcp0qZ02yKWwTuQQnsNMSMqnALkuKAaNoXky1czOapCsbsTsUm+JjBrLHsZZUbxVM1PO7BpO8ppOV1nRUQm+5cLtGc0p1eFXrRcSn5YKz2dNileNDfAE08qIUjixQct4UXht8SrwEXLu8iV4NIs2R/8haIlM6oV3d1E5QGpeCLV4k5O2JKvSPzzUxR7v6gbt8FMtlKtpzXmJhgNvbs0sK4m/n/HYhDEqWsnIq4EVSF1Vq44DoY25cfTFVehVYQDH/UEaJmnC4jjwB36UJN3WEfXTJAhjFgeJn0ZJP24d4TCOEt9nCZ1REIWDqLIf1V5tBJJ0X7T9hjUpU0EMftdSts0jNohjn/qm/TgI0vRfj2Of9YeDcJhGdAbhcBgOWk/AwngQJIS0HydJGCQhHid7ACRkqFhslKFt+WUtZNXYzt5TyfVB4JndqbzhkH6v5NaKe5HXE812K9q/PZEvXGx8cXP54+o2PL+dXU4u2rV6T12vAGw2MVOdbmdk3U7iaYME4LMoV9o4WBvpMdZzWNIu0r/szde0zY7l1jZ6Bhj1DlNHhdiAKE5eeVyaAclzv5byRvzBrHM66lH8i9RW1dcbNPQCVGHL4HTSGBljox5dX890Wss5N88q/wU)

Everything is kind of broken visually, the OSM data should be draped over Google, instead it just appears to render incorrectly.

To make sure this was a problem with the OSM tileset and not google, I took our basic classification example and used it with Google and it worked as expected (though it doesn't full line up this is a data problem). [Link](https://sandcastle.cesium.com/#c=xVVRa9tADP4rWtiDA8beFvrSpmVbUkahZYWkezK0F5+S3HY+hbtzSlry3yf77DVOk/VtA4Ox9En36ZNOzsk4D2uFj2jhHAw+wgidKovkR22Lsl5ef4/IeKEM2qwXw3NmALwqULPlFOZCO4wrmzCqEF6R2TW6HA3ekMRblf9Cu+uaCYfXYoN237Xtn2UmM2kK0yXCQtMMQRI6MOSZJUrwBJVNuZXmBDKuwU6ZHMFzyO2SPFkUWjmvchiMYao0xzNAl5IxaC3Xk5lQe1KTTOqDErekRxaj5tLS+CLlsZyZ8XYTNMlrOX1lRc8pxKNQvlU051CP34gWGrupBuNpCImqsgE6nFZWFcqrNbpESBk1yYM+7Ym5Fs6pucpr8Ztkd1bDeYUByHpJkk5EsdI4Fl6kgVFzbDrqRKc1t4UVRYFcWNocmPx0ZLJeza/SA2YDWfwptXShJQ2RTd2DVSdRi32D9b5qHapMY26p4MqiUNixwuPgfg6vV7jNise2PeCVKxldTq7ubu4H4/vp1fVlk2tbvUJ/Dp6aOL/R2L1Eu+QnlTtqGOWkicc969nFTESfTk5i+BCe5KTPV6xCbd8ehoNE2tFoLo8TBR5o1pzsXh0xzEoPFo1EywBDthBabwKSipWwikcgeemfITP6dy2sbuXu7uh05BiV/9GUY1w6kU9ExZT+3sCJMDIXzmus8k5pwYvja+k9GV7Lk2pJdcOr1extiTHMS5NXFmg1XiLvV1nr1Sp6ZIjD7msCzgL0uLoB/W4XXiu0BQbmS4h4zZLtv2xH4mI0LaKHy8oBmoRUZtGO5im8f64jtg8hSy/uDesWXrRj8FkVK7I8xDxAvNQ88lLjterSWckUfJI7129oD9Pd0KFUa1Dy/MAfLWjBnnmp9UQ9Yda7GKaMfxXa8P2+Rsu/nQq2/HhxHYxJkgxT/jwc6Yn0TNi9zL8B)

### PR DESCRIPTION
**Pull request by ptrgags**
# Description

After investigating #11341 and #11223, the result was that these are limitations of shadow-volume based classification that were not well-documented. The two examples had two different issues:

1. OSM buildings is not watertight (most buildings do not have a bottom). The stencil test used for shadow volumes assumes that the mesh is closed (so there are the same number of front and back faces to render, so this causes the coloring to be flipped for some fragments:

image

2. For the other issue, the problem happens because the tileset being classified has translucent primitives. Since translucent primitives do not update the depth buffer, the stencil test will give incorrect results. This leads to artifacts for some camera views:

See [This Sandcastle](https://sandcastle.cesium.com/#c=fVZtc+I2EP4rGj6RKZVtDDhwSaYZkuaYSXrpQK4fmk5OyDKoJ1uMJMORm/z3roxtZIc0w8Ra7euz2l2JykwbtOVsxxS6RBnboSnTPE/x12Kv+9yhBT2VmSE8Y+q500M/nzNU/vGUrJjaPyq55TFTE9fEtaJ3XD+QzZypLVOzpmjXsYJQrsTEpRF67qyN2eiJ52lQ5xAGJoquuJaZgEAwlalnPczmnmLa1FLeX1KJ+KX05tXuIfCjg7ezmng7+1QtBTPIcME0fC/LrGBNGXjbKJ5yw7c2ijjuHi2RHeGmQnz4hDeLgxGcKJk+KdH9CBnlKc2XDK+EjGVWQFomFo7MFWUeSdiInQ9GgT8i4yENh/EgGNOB79PROPGj0VFyG3phXITulQDwv5CoBuazamkBV+tKmubayHS+JnG7EKYOxz0zz0NPGUScsgyytuYa2WNBRqKE/0BEGZ4QajSK82LTKJJpkVMrvQGuRjIBNYaWORcxz1bYNX2UpvsHGbPJqWgWLSH85fH6z6dbB7Lgq7UB25Yrahv37i5++uN+tnB0EkVWFlPpg/0wE/TNPUAAPpVCqkPu0HKPYq4NyegBJ0CiJGWKuDpbyePa8gM0Uvf3kphlm9ygRBffHuKZBJK+pi+pje6BGKY4ESgtF2eu1Z/NukK1FI55kuSa2SpmNOz62O+h4l+A/WO9f6SGV6D4axkTJsYovswNlP5GamgCmd1O8SvyrDE2aFh7c4lvzR6riKNI2WGvUqYL2S1L0RW1DVn51BDT30fdwA/x+XkQBefDaBj2R2PnCEMfD0bD0O9Hg7Afjf2g19KLojAcBePxMPDf6fUHYTQAvh+d99/pjYNBGETDUTgM23rBAJhRfxhG4/GR+U+dHhdHVczQB7AiWVhMihu2Uozpa6XIvluLt/MBBanymMWPUuxXMms2a7l5x2TKjNq7/bo5sD5zKE1F1/vJCb2a6bh3cK6Z7ZwJCobOZhXP55qJfoFs+f7p07cQNLSW3H2VIk9Za9gIojVPOCXW+WM1dF0cqxLbLDs0nW4AuWtxm7dMpTv5IF+YKga9UKevlWs3FzD5676YtDuR2vlwnFmWagd2XWkXR1+IdNt96SamEAigi4ufbeOmdDM2BDmWu0Zm5rDxYRBdwMmaJt4aFI8ncG8BVvPRPQoJ0fuMrpWEEQYpSYjQzOUKIXePnH6HyTtB1l/Pnfi0cfKL/caZ+e9YeHo7nz09vIQ3L4vZ/e2pu/z/bm+3/tza3PEM9nH9HDosPnV6nQtt9oJdVYK/8XQjlbGvli7GnmHpRkDdaG+Z0+/2NtW6iuTCc1UvYr6FXF6eeFahIgPASXIh5vyVPXeuLjyQf6cqJLEX5hd41Aiyt2Lr4Or+sIkxvvCAPK1ppBRLolqW/wM) for an example

| translucent building (has artifacts) | opaque building (no artifacts) |
|---|---|
| image | image |

This PR simply documents these additional limitations of 3D Tiles classification.

## Issue number and link

Fixes #11341 (by documenting the limitations)

# Author checklist

- [x] I have submitted a Contributor License Agreement
- [x] I have added my name to `CONTRIBUTORS.md`
- [x] I have updated `CHANGES.md` with a short summary of my change
- ~~I have added or updated unit tests to ensure consistent code coverage~~ Documentation-only change.
- [x] I have update the inline documentation, and included code examples where relevant
- [x] I have performed a self-review of my code

### CODE REVIEW

File: packages/engine/Source/Scene/Cesium3DTileset.js [hunk 1]
```diff
@@ -1635,6 +1635,7 @@ Object.defineProperties(Cesium3DTileset.prototype, {
    *     <li>The glTF cannot contain morph targets, skins, or animations.</li>
    *     <li>The glTF cannot contain the <code>EXT_mesh_gpu_instancing</code> extension.</li>
    *     <li>Only meshes with TRIANGLES can be used to classify other assets.</li>
+   *     <li>Meshes must be watertight</li>
```
Comment (ptrgags) [inline packages/engine/Source/Scene/Cesium3DTileset.js:1638]: For consistency

```suggestion
   *     <li>Meshes must be watertight.</li>
```

File: CHANGES.md [hunk 2]
```diff
@@ -15,6 +15,7 @@
 ##### Additions :tada:
 
 - Vertical exaggeration can now be applied to a `Cesium3DTileset`. Exaggeration of `Terrain` and `Cesium3DTileset` can be controlled simultaneously via the new `Scene` properties `Scene.verticalExaggeration` and `Scene.verticalExaggerationRelativeHeight`. [#11655](https://github.com/CesiumGS/cesium/pull/11655)
+- Added documentation for `Cesium3DTileset.classificationType` and `Model.classificationType` to clarify additional requirements. The classification tileset must be watertight, and the receiving tileset/terrain must be opaque.
```
Comment (ptrgags) [inline CHANGES.md:18]: Add PR link

File: packages/engine/Source/Scene/Model/Model.js [hunk 3]
```diff
@@ -1550,11 +1550,15 @@ Object.defineProperties(Model.prototype, {
    *     <li>The glTF cannot contain morph targets, skins, or animations.</li>
    *     <li>The glTF cannot contain the <code>EXT_mesh_gpu_instancing</code> extension.</li>
    *     <li>Only meshes with TRIANGLES can be used to classify other assets.</li>
-   *     <li>The position attribute is required.</li>
+   *     <li>Meshes must be watertight </li>
```
Comment (ptrgags) [inline packages/engine/Source/Scene/Model/Model.js:1553]:
```suggestion
   *     <li>Meshes must be watertight.</li>
```

**Comment by ptrgags** [comment]
@ggetz could you review?

File: CHANGES.md [hunk 4]
```diff
@@ -15,6 +15,7 @@
 ##### Additions :tada:
 
 - Vertical exaggeration can now be applied to a `Cesium3DTileset`. Exaggeration of `Terrain` and `Cesium3DTileset` can be controlled simultaneously via the new `Scene` properties `Scene.verticalExaggeration` and `Scene.verticalExaggerationRelativeHeight`. [#11655](https://github.com/CesiumGS/cesium/pull/11655)
+- Added documentation for `Cesium3DTileset.classificationType` and `Model.classificationType` to clarify additional requirements. The classification tileset must be watertight, and the receiving tileset/terrain must be opaque. [#11739](https://github.com/CesiumGS/cesium/pull/11739)
```
Comment (ggetz) [inline CHANGES.md:18]: Since this is a documentation change that doesn't affect the typescript types, so the public API is not changed, I would suggest omitting it from CHANGES.md.

**Comment by ggetz** [comment]
Thanks @ptrgags!

**Comment by ptrgags** [comment]
@ggetz updated!
