### PR TITLE
fix(textureatlas): Apply internal padding between images

### LINKED ISSUE #4525: Outline around label's characters and billboards in clustering demo
I often (but not always) see gray border around characters and billboards in [clustering demo](http://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Clustering.html&label=Showcases):

Tested on Ubuntu 16.04 with Firefox 51.0a2 and Chromium 53.0.2785.143.

### PR DESCRIPTION
**Pull request by donmccurdy**
# Description

The texture atlas used for billboard rendering has 1px padding enabled by default (`borderWidthInPixels`), but the padding is only applied around the edges of the atlas — not between images. I believe this is the cause, or at least a cause, of #4525. This PR introduces internal padding, so that the existing option affects spacing between images in the atlas. Image subregions have no padding and are unaffected.

Screenshots:

| before | after |
|--------|-------|
| border_before | border_after |

## Issue number and link

- Fixes #4525
- Fixes half of #5154

## Testing plan

See unit tests and #13037, and:

http://localhost:8080/Apps/Sandcastle2/index.html?id=itwin-feature-service

With 'points' (pins) enabled and all other features hidden, this is a good example showing the top of one pin bleeding into the bottom of the pin above it in the texture atlas.

# Author checklist

- [x] I have submitted a Contributor License Agreement
- [x] I have added my name to `CONTRIBUTORS.md`
- [x] I have updated `CHANGES.md` with a short summary of my change
- [x] I have added or updated unit tests to ensure consistent code coverage
- [x] I have updated the inline documentation, and included code examples where relevant
- [x] I have performed a self-review of my code

#### PR Dependency Tree

* **PR #13038** 👈

This tree was auto-generated by [Charcoal](https://github.com/danerwilliams/charcoal)

### CODE REVIEW

File: packages/engine/Specs/Renderer/TextureAtlasSpec.js [hunk 1]
```diff
@@ -832,16 +832,16 @@ describe("Scene/TextureAtlas", function () {
...
-•22222222222222223333333333•••••
-•22222222222222223333333333•••••
-•22222222222222223333333333•••••
-•22222222222222223333333333•••••
-•22222222222222223333333333•••••
-•22222222222222223333333333•••••
-•22222222222222223333333333•••••
+•2222222222222222•3333333333•0••
+•2222222222222222•3333333333••••
+•2222222222222222•3333333333•1••
```
Comment (jjspace) [inline packages/engine/Specs/Renderer/TextureAtlasSpec.js]: When I reviewed #13037 I assumed this representation is "top down" as it would be rendered. However if I understand the change here (which I might not) this seems to be adding an extra row of pixels to the "right" in this representation but the "bottom" in the actual billboard. Do I just not understand how the texture atlas works? Or should this representation be rotated?

Comment (donmccurdy) [reply packages/engine/Specs/Renderer/TextureAtlasSpec.js]: Ah, the origin is bottom-left and I'd assumed top-left. I don't think that changes anything implementation-wise. But certainly debugging will be easier if the test output uses the right representation, so I'll update the test output to match.

Will respond to the other part of this in the main comment thread.

**Comment by donmccurdy** [comment]
> I see that adding padding to the atlas works but that's just filling the last row of pixels with transparency isn't it? 

@jjspace previously the atlas put an N-pixel border around the perimeter of the entire atlas, then packed billboards tightly inside of that. With this PR the primary goal is to have interior N-pixel borders between billboards as well.

Implementation-wise, there's more than one way to get there. TexturePacker.js implements [binary tree bin packing](https://jakesgordon.com/writing/bin-packing/), where each time a billboard is added, we find an empty rectangle (the large outer square below), insert the image (yellow tile below), and create two new empty rectangles in the remaining space for future use:

large square divided into an image tile surrounded by 2 empty rectangles

> Image Credit: Jake Gordon

The solution in this PR is that each time we do an insertion and create those two empty rectangles in the remaining space, we offset them from the inserted billboard by N pixels so that space isn't considered available:

split_annotated

Entirely possible there are other better ways to do this! With the visual tests I'm hoping it will be easier to see the tradeoffs if we decide to change how the padding is handled.

***

> Would it be better to say that the billboards are displaying 1 px too much from the atlas?

I think it's a combination of linear filtering in the texture sampler and perhaps some numerical precision limits. I also tested switching to 'nearest' filtering and while that definitely reduces the visual artifacts here, it doesn't solve them entirely (which this PR does, as far as I can tell). I may do a separate PR for the texture filtering, but that has other tradeoffs and wouldn't be the right fix for this specific issue probably.

In https://github.com/CesiumGS/cesium/pull/13020 there was also some discussion of mipmapping billboards, and padding between billboards would be a hard prerequisite to that.

Finally, I suspect this may have been the original intention of the TexturePacker.js `borderWidthInPixels` option? Or at least I can't think of a reason that padding on the atlas perimeter would have been useful without also including internal padding.

File: packages/engine/Specs/Renderer/TextureAtlasSpec.js (hunk 1 above)
Comment (donmccurdy) [reply packages/engine/Specs/Renderer/TextureAtlasSpec.js]: Both PRs have been updated so that the `drawAtlas` test output matches the coordinate system in TextureAtlas.js, origin = bottom-left. Thanks @jjspace!

File: packages/engine/Source/Core/TexturePacker.js [hunk 2]
```diff
@@ -130,12 +132,18 @@ TexturePacker.prototype._findNode = function (node, { width, height }) {
...
-        width: widthDifference,
-        height: nodeHeight,
-      });
+
+      // Apply padding only along the vertical "cut".
+      const widthDifferencePadded = widthDifference - borderPadding;
+
+      if (widthDifferencePadded > 0) {
+        node.childNode2 = new TextureNode({
+          x: rectangle.x + width + borderPadding,
```
Comment (jjspace) [inline packages/engine/Source/Core/TexturePacker.js:141]: Given that border padding is a dynamic value would it be good to have a test with at least one other size than 1px? Maybe like 3 or something? just to prove it's working in a "non default" case.

Comment (donmccurdy) [reply packages/engine/Source/Core/TexturePacker.js:141]: Good call, done! New test case: "adds custom padding with borderWidthInPixels".

**Comment by donmccurdy** [comment]
Added the new test case, good call on that, thanks @jjspace!

**Review by jjspace — APPROVED** [review]
LGTM, thanks for the updates
