### PR TITLE
Fixed JSDoc definition and EasingFunction typo

### LINKED ISSUE #9046: Viewer.ConstructorOptions has incomplete JSDoc/TypeScript definitions
In [JSDoc](https://cesium.com/docs/cesiumjs-ref-doc/Viewer.html#.ConstructorOptions) property globe is only typed `Globe` but should be `Globe | false`

This is only defined in the description 
> The globe to use in the scene. If set to false, no globe will be added.

Therefore the TypeScript definition is wrong.

### PR DESCRIPTION
**Pull request by benjaminabb**
Fixes #9046

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @benjaminabb!
* :x: Missing CLA.
    * Please send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/master/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA) and comment back here to let us know to check this!
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/master/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by benjaminabb** [comment]
I updated my CLA because I renamed my GitHub account.

File: Source/Core/EasingFunction.js [hunk 1]
```diff
@@ -22,21 +22,21 @@ var EasingFunction = {
    * @type {EasingFunction.Callback}
    * @constant
    */
-  QUADRACTIC_IN: Tween.Easing.Quadratic.In,
+  QUADRATIC_IN: Tween.Easing.Quadratic.In,
```
Comment (hpinkos) [inline Source/Core/EasingFunction.js:25]: @benjaminabb can you back out the changes to this file into a separate PR?  There are a few more changes we'll need to make regarding fixing this typo before it can be merged into master

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @benjaminabb! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @benjaminabb! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by cesium-concierge** [comment]
Thanks again for your contribution @benjaminabb! 

No one has commented on this pull request in 30 days. Maintainers, can you review, merge or close to keep things tidy?

 _I'm going to re-bump this in 30 days. If you'd like me to stop, just comment with `@cesium-concierge stop`. If you want me to start again, just delete the comment._

**Comment by OmarShehata** [comment]
Thanks @benjaminabb ! Confirmed the following code in TypeScript doesn't work in master and is fixed with this PR:

```
const viewer: Viewer = new Viewer('cesiumContainer', {
  globe: false
});
```

Confirmed we've received your updated CLA. I've pushed a note in CHANGES.md about this fix.
