### PR TITLE
Fixed displaying Cesium Ion icon in WebView

### LINKED ISSUE #8665: Cesium ion icon missing, or handling file:// base URL
I'm hosting CesiumJS in an Android WebView where the base URL is file:///android_asset/. In the view, the Cesium ion icon is not shown, due to an error processing the base URL.

Sandcastle example:
https://sandcastle.cesium.com/index.html#c=ZZBda8IwFIb/SuhNK2wJu3VV5ooXgjKweFeQ2By7sDSn5KPixv77klo3t+UqH+/znHPSc0OOUsHOSDIjadxOGWNcC4NS7Lm14FjLO1aAlb5l6WOlK32SWuCJFstytdvsnxflcr/broNgVA2hGrVFBVRhk11oevBSiQ0KH1MqSxdRb9mq5Q1YJlHf1waEdLTTTTqZDJo+dGjAojc1hAoaTmS0bcfb7IN4o6bfc3xG8Lb6Fach9iP1w8g3vsBmo+OvIWSpw9IZqZtsaCy5S3LrzgrmlSZhPcm2Q+NiJxmlzEHbKe7CVAdfv4GjtbURy9kVyoXsiRSzKqmH8gVqx6UGUyWkVuHjw8vRK1XKd6iSec5C/hemkIvQzksPRvFzjLw+zNeXS0ppzsLxP+UQ1YGbG+MX

The file:/// URL is changed to file:/, and the icon can't be accessed anymore. Interestingly, all else works without problems.

Browser: Chrome on Android, Firefox on Windows

### PR DESCRIPTION
**Pull request by vividos**
When running in a WebView on Android, iOS or UWP `WebView`, the base URL either starts with `file:///` or `ms-appx-web:///`. When the Credits object for Cesium Ion is created, the `` tag contains a `src` attribute with this base URL. The integrated `DOMpurify` strips all src tags which doesn't contain `http` or `https` URLs. This fix changes the `src` attribute to contain an absolute Url in that case.

This PR doesn't need my other try at fixing the Ion icon issue, PR #8669, as it would also work without it.

Fixes #8665.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @vividos!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/cesium-ion-icon-webview/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by vividos** [comment]
@OmarShehata Could you please take a look at this PR and test it with your Cordova test app? Also there is an error from the Prettier tool that I tried to fix, but unfortunately the tool doesn't exactly say what the issue is. Thanks!

**Comment by vividos** [comment]
@OmarShehata  I finally got it working with Prettier not reporting any issues now.

**Comment by vividos** [comment]
@mramato @lilleyse Maybe you could take a look at this PR and consider it for the next version? I'll rebase it on the latest master. Thanks!

**Comment by OmarShehata** [comment]
@vividos thanks for continuing to investigate this. I can confirm this PR fixes the issue on Android with Cordova and makes the Cesium ion logo correctly appear.

@mramato this is the correct approach as far as I'm aware but would love to get a second opinion when you have a chance to take a look. This requires a change in ThirdParty code that we're using to parse URLs which is producing incorrect behavior as I mentioned here: https://github.com/CesiumGS/cesium/pull/8669#issuecomment-606584921

> For what to do with this PR, @mramato the behavior for parsing URIs with file:/// (three slashes, no authority or hostname) is incorrect in master, and is fixed in this PR. Sandcastle with test case here #8665 (comment).
> 
> I'm not aware of a way to fix this without modifying the third party code, since ThirdParty/Uri.js incorrectly skips the // when the authority and hostname are blank. I would merge this after unit tests are added for it but wanted to get a second opinion here.

**Comment by vividos** [comment]
@OmarShehata A short comment from me, this PR only changes CreditDisplay.js, where the `<img src` is specified. Using an absolute path, without file:// prevents the DOMPurify to remove the src attribute altogether.

The other PR from me, #8669, is not necessary to fix the Ion icon, and that PR modifies the third-party code.

**Comment by OmarShehata** [comment]
Oh great! My bad for missing that @vividos . This change looks good to me then, and perhaps we can revisit the `ThirdParty/Url.js` fix when we have more time.

Congrats on your first merged contribution to CesiumJS Michael!

File: Source/Scene/CreditDisplay.js [hunk 1]
```diff
@@ -512,6 +513,14 @@ var defaultCredit;
 function getDefaultCredit() {
   if (!defined(defaultCredit)) {
     var logo = buildModuleUrl("Assets/Images/ion-credit.png");
+
+    // When hosting in a WebView, the base URL scheme is file:// or ms-appx-web://
```
Comment (mramato) [inline Source/Scene/CreditDisplay.js:517]: I know I'm wait late to the party here, but would setting CESIUM_BASE_URL to the http scheme be the better answer here and negate the need for this check?  Or is logo special and is the only thing that doesn't work with file://?

Comment (vividos) [reply Source/Scene/CreditDisplay.js:517]: In my project I host the Cesium files completely in the app, no files are referenced from the internet (except, of course, files from image providers). So setting a CESIUM_BASE_URL wouldn't fix that problem. The Web Worker files are loaded differently, I guess.

Comment (mramato) [reply Source/Scene/CreditDisplay.js:517]: Thanks for clarifying. It still feels like something strange is going on but I'm okay with the change in the meantime.
