### PR TITLE
Fix rendering for instanced models without normals

### LINKED ISSUE #10764: Error LegacyInstanceing without normal
# Error legacyInstancing i3dm without normal vertex attribute. (in main branch, 1.97)

https://github.com/CesiumGS/cesium/blob/85535fbedc196ef872f989d9a81ef22161f16193/Source/Shaders/Model/LegacyInstancingStageVS.glsl#L7

# My Fix 
```
//(original) vec3 normalMC = attributes.normalMC;
=>
//(fix)
#ifdef HAS_NORMAL
    vec3 normalMC = attributes.normalMC;
#endif
```

### PR DESCRIPTION
**Pull request by ptrgags**
Fixes #10764

There were a couple lines in the instancing shader about handling normals that should have been wrapped in an `#ifdef HAS_NORMALS` guard. And the legacy (i3dm) instancing shader had a line of dead code that should have been removed.

[Sandcastle Example](http://localhost:8080/Apps/Sandcastle/index.html#c=tVdtb9s2EP4rnD/JgEvZTtx2nhMscdYXbMm62i0GzEPBUCeLCEUKJJWXFvnvO1KSLb98MTIHAULekfc8zx1JXbhW1pF7AQ9gyBlR8ECmYEWZ06/BFi06PMynWjkmFJhFp0d+LBQhQqX6Uj+OScqkhZ43WZDAndDqo0oEZ06bDW/GEv1gx8SZsrHoUiYXSuTMwcr+3P1loRYqLVWIRbgBdF/rBGRUGtkjGYhl5roVjYo7BeWEE2CpgVzfw4WUURWGEB40FtqKEO6sUThlxuGIqROaGp1fwdIA2MhvIeTVYHhC+29OT18Pfu5VptNT2h/1T970X9eGiocfe6gGKAOWCLVc41wzl1GnP6OZKRsNTkbt5YVwPMPF/ZbNaCm3TFmxVZ8PFcwnv/0zro9q3F4VsReCtIG0EZgktpmDuUFKqTa5pdlWwL9KzLpRuLxOSZPBRn1hGulrkFCGJ4y/XRaWJNGPaqNiORbbV3Iz7ngbocV43J7U7tyfiDGpoxKMKNphcYHAk1Xmn8QjyJn4jqCD4du1lz1674wziZ5hH39q33P4+1wlrxbiDON3kPzW6KuE4opnL7/OcOHZWfT+43fWxBw8ujFZdD7iEqY4JARvDYluNLnBvOPt6OKVqgWr6gbhrWkOf9RdC2xfhMZGMHI8K4Db+Io5FgevjZdy/u7VkPZjxFoB3+gaMbj3u+hSunRFyP8MRs24SsgqP709Ii+E4Yal7qWSKI3xd8byQkLQlVe6qmOLKPXoGw6R8u0G4xGWkvYPYH1ltILjUg4Q7fEO68HoMNLvjS5VQr5CJrg8GvsKpQbZnO0oOIT9B+0I1o5cMim1VsdNfg2yOdstwKHH5lrIOzI3Jb87Ln2PE2C25y+qwOxOKIWv0TRj+La58GU/pgjW5P8bDl/E/IuSwvlX9FiMMXTAWA32vIqHvjCMazLVeWHAWsx6IHMs/gFtDbbn2GypOUTK7/O/h20lB95gkZLop7r7eIeySgNX4Kq2kdqyKLRx9pJZYaP602s5KOi2QhDyIBS2khS/3Ma1MuJzMs+EJbcGG03saBMNlih8aurAJAQmX5S4B2OZxK5lpcPrQzJ20VkHbNKBqfhfXiCfu13Ly1+ijd7iiLdihbMxOaxn+Dc0jDOmEs6sw88ItoZzreUtM9egyqjuovzGTq8zse5JwnkT7leRhzpimxchSQdIEkXY+BbPNTjKrW0QJ3F76yQR90QkZ3v+nyFcMmvRk5Yy9ImLzvkkxvU7W6UOLfKfeHgke/LLssH5H5WRUjqJcbp/p6sEbkX+Dw) -- the shader compilation will fail in `main` but work in this branch.

@sanjeetsuhag could you review?

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @ptrgags!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/fix-instancing-no-normals/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

**Comment by sanjeetsuhag** [comment]
@ptrgags 
image

 Is this jaggedness expected?

**Comment by ptrgags** [comment]
@sanjeetsuhag I looked into this when the model doesn't have normals, `ShadowMapShader.js` skips some code that shades based on the normal direction, so it's not going to look great. I'm guessing that these jagged line artifacts are related though not 100% sure

File: Specs/Scene/Model/Model3DTileContentSpec.js [hunk 1]
```diff
@@ -535,6 +537,15 @@ describe(
         });
       });
 
+      it("renders without normals", function () {
```
Comment (sanjeetsuhag) [inline Specs/Scene/Model/Model3DTileContentSpec.js:540]: This test fails even if I remove the `#ifdef HAS_NORMALS`.

**Review by sanjeetsuhag — COMMENTED** [review]
@ptrgags The code change looks good. There's a spec that's not catching the original failure.

File: Specs/Scene/Model/Model3DTileContentSpec.js (hunk 1 above)
Comment (ptrgags) [reply Specs/Scene/Model/Model3DTileContentSpec.js:540]: This test is using an i3dm tileset, so it's using `LegacyInstancingStageVS.glsl`, not `InstancingStageVS.glsl`.

If you were to add a line to the legacy version to include `attributes.normalMC`, then it would fail

**Comment by ptrgags** [comment]
@sanjeetsuhag updated!

**Review by sanjeetsuhag — APPROVED** [review]
Looks great. Thanks @ptrgags! I'll merge once CI passes.
