### PR TITLE
Prevent `Model` from resetting draw commands for picking

### LINKED ISSUE #10625: Setting style of `Model` before it's ready causes an error
Setting `model.style` before the `readyPromise` is resolved leads to this error:
image

This is because the `style` setter doesn't check if the model has loaded or not, so it's trying to work with `undefined` components. It'd be nice if this were consistent with `Cesium3DTileset`, which correctly applies the style once the tileset is ready.

[Sandcastle example](https://sandcastle.cesium.com/#c=tVZtb9s2EP4rhD/ZQ0JLfo+XBkuTNOvQoEHsdcCmYWCks0WEIg2ScpwN+e89kZIsJ+7apohhy6TuePfc3cMjYyWNJWsO96DJGyLhnpyB4XlGP7l37agVu/mZkpZxCTpqHZD/IkmISVUuklPJM2ZhSqzO4SCSj52fIxlJb5HGQsV3NM61BmnnPAP0Udr/LRecyXNcSxdaZe+NmoyCsF1Yjlq9oBcehuFhcDTvBdPeeNof0yAcBaPBYDzsDyajyeCoP/4zakXS++t2yZVKQJhIxi6kzM3Q3V+FRQeYEAsbO0XzHgJ5y4RQSmJEXowLQUCMKotcxpYrSdqdai0G7ITOTbt6V4CltDtj2UoABsO63nHXuyg97M7oUtzWPotPOKzGRTDF/6OT+ucT7LM7LiUk5CxlmsXWFeS14F+xCvo/OHyGO/gO2OcIVpEzla00GIP4HZBXwe5cbT1VsXBxN9c50nEp7OLFcfwuBbfkrdq8CPp+wGjNma0HFUQSfFNmlYRXJIGz3xz/GH8vtcplQj5BymPxOri9i9LD7uyHOPweGwuTMZL3pfX/GnK0WzvZmTwn7f8l/W/XE30jTFdPGvuvwBIul9fcxumNEh5VKbtiNqVW3aAGk6YdToKOMxr4p++23u6CbyB5p1kGc426C6WzbXOvXxmKJwATXk+9q9dcAh4lzCpdNnyptE3L+KLWPRi77e11WpupzLU4ICnwZWrLZHtYK2W4U66xnDFtccRk3x0057DUAKasxWHY69NgPBiMwqMyuYMBDYZBfxyMyhfeSzH2eEh5XlITYxR0pXmGLtdgqIZMreEUc+pr0jiKEM+XVrEkKdFUVSgWXGxWgDp4bjLhgF8iA9o1rTD+afGoGeG8YP0030z3lCF9UvVmMRq8rNLXIBoSqDErLV8IwVdG8YT+cTmbDBoKe3hRE3ULluO1Ic+uUVfM+L94fQh7k62UbQrpDImDkl6An1L22KnKgDTBHx7785QbErPcgCFMEtBaaVrIXEKosQ8CdjeA/+ufz7mAWSGushoroXSx0fXylrV7wyE2YP+lw05JzseKA968xrQ+XGN1uAFqU5DtbRNwGnUnqG5EmBjNcFeou1NbJ/5Z2r+0X5lcNsu1f9sOhp2Dr+kchjtKPprbolOir9kqBQ1Uo25uyE9k22r8oMpBtQ7vIchkfxXEKByli11QsxXDXU136F0rf0ARvbm4vjid10UuG5p/VjXG7wIvoLTp+Huq+231rd27v8cizhmTScyMxdMD45orJW6ZvgKZ+wobn43WQStq1cT0po4dvpPK/y88W2GfK7ZtG9u/BWz/eP813Vu8loClsTFV6Mfd5tLjhK8JT97suYyTWDBjULLIhdtKUevkuIv6z5YK5Xj0cQ1asIdCLQ1PPviXlNLjLk73r7Q+5CeWPwM)

### PR DESCRIPTION
**Pull request by j9liu**
This PR refactors `Model` such that it doesn't `resetDrawCommands()` every time a feature is picked and colored translucent. Here's the [local Sandcastle I used for testing](http://localhost:8080/Apps/Sandcastle/index.html#c=zRprc9pI8q/MUVsJ7BFZ4o0db52NIeYWP8omm9sLKUdIg5nzaIbSwzab+L9fz0NCQpJN6rxb5w8Y1D3dPT39Hu3toWuboZFvM4cEDkcj7PtrdBwR6hJ2i1ZLHvJb3/Y8HMJzj7uYopXP74mLXTRfoyPscwHDjzPmcBaE6J7gB+yjQ8TwAxrggESe8Zt8Vp1VHPl7wFloE4b9WaWOvs0YQiGwhSeXirK/Hy90fGyH+BP3qTtVKNVaXSwgbMGP+eM+Wtg0wPIR92HlmLl4heGDhVPYVEAjBzNnvcF7qh3M2IwpKQ2HcufOcCLfFwuIh0FuzfqfESU2OwH2xgL2OA54r2NaVcFpVmmYDeudZb0z+9OGud/o7je7hml1zE6r1W03W71Or9Vvdv89q8yY4qd0E4AwgoXmLn+mwCGhOMBhVnfqX/NkqoBVqa/Ip4mOxpxd4YBHvqMkPQoAbexWu912r9utbfasmUi12CHhbIuR7YfwzWZNucl3ltHs99oNq9lo9Rtmp9GRWjaNbq/RNNuNXtfqNvqw1fixabUbrVbLMtv9Rsfsq53rLRnScs7s0CePGxWr3y0p9XQjVjUlopI8oWI/Ei/yrsEsMLte2Q4e+j4XxtYzTMCUCjVWxLnbHH54glfhElBCP8IJDiW3y9AgLMQsIOEawF1JIbEMTconHgnJPQ4M23WrWg4hlEb7g4PoPA2Ysb09NKJrFHJkI0YcjPg99gU+4gsULjFygKOxsUHbw75tLOgaCMnTdXEQEib3v//MCcEZNbpms9MyjZ7Z6rV7LXUW8LzV6FhWxzL6fbPZarc6LQ1o9nrdVrNvtC3LMluNbkc8rmn3IaCsPNNTbItQcElCZ3nFKdWsTaPRAC4doNRqtpvtdqsXMwdQp9GyWu1mp9E2O+1Gtx6vMcVfpw+G0+02Gk0L7KvZj2V4StR3Ha5Bn+jwNf82HuBQOwjIgjhys5JXuctJsDoWh1MOoQmimPhS/emb/P9UgyhW6GPS+j4R5vKH4Ie5fFMqA3ouEWIG++jz51lFMPVWnAHlJ6Ef9FYzeCtiaSzaWwjZ67d14ZUg3ZcvUv9PWRUvbQiXr6tjTfok8rw1CiQDsHcb4h4OA2n5H88n4ymSzifSi4gKBhqBB0cBRg8E/FT6R+aAUCCUE6sWe6twDfnq1gMVqE2gQxWU7zlx0UKDzkSuiPHGbBWFaBHI/3VIHhx+On94N3FYwj6xKfL0lxr69jSrHMQsI0ZJwipzglEQck9B1OHFOzsTdJMIPUk/NaQO5IksMtuY4sdwv2h/29YVi/l6Il0eX5UK9DUxRGANARN9Gp+fXHwCtiJeZkGjq6OzIUCsHOTT0WQCgEYOcHVxMQJAMwe4/vX3yfjD6RSArRzwaHx1M7g4PxlPxxfnw6ubT6fjqWDcfhHzeHI0+BUwOy9iTpXI3RziYHIhSfRykMvxZHJ0dQ2wfn4/06vhcHoT78nKa296dTQajQcblFiN6vM1zVtRRJLtAkqsyMdjF1hqGkbyLNh8vTEz4sDiBaqmFh8qxaSoIyQDDWFrNPfBpTfPY1GMYIWdiNrCiu+x06yaRr8n4lbfFJ/tfu2gYJHPo9slw0EgjNCwEpQnhKHIk3JtVmUkzBzC9+8lWMU2szO6Msad0aWdlWIL/4hB26p1I0qRTSOPsMjbTbmWVG5Dfe6g3HaRcjMC6nDw/fuWprX7bsvs2Xc4nR/raA7GCsU5F1kCQTPCAXiLIRASSAL3WCVEBHASIsr5XQAh7Q5niJLwrXgKtgyVJBh1AE1EwdYSklofliGtrCk+zEJl2HS1tHdVhDrHrBpURNx+quPEtm5WtvBHkQEfbEoDUIaLVoTCCQboYUlCLGpKiBegvkDhSbdCsospkN4li4VIrIfII4/V7cf1RAk1oYDeDtbQ31ZCVv65L7IKZghDwbsOlyLFC7RnRPu7IGu2f4i1+qL/fd3OjucX09Px+Yeb6+FkOJgOT0QgbSS5PMAUO+FIHcZuCTRiZMF9L0hqsuhGUcGuprO/0UO4XuEkyX5UK6fwzBifT+sx0j34LGBtS6rhT0m19ick7zLt/N8mmJyy0fv8Jt68yfpXblHG00rjI7iCDAi9tkw+3R9LPs+bpRfRkKwoHiUb/yutbzS5OPqz7O/5ejZngeOTa/PmmRoS4NbN6GhwdDIsLBglvLBqFGeILj9eXU6Gm4wnjxJO1dpE+BT278PJRMqxyQc6KRRhn1/cTMGPU+i1v7ZCM1/2IBGHF4TheFFQSMh6iZAlCTkcUs82qZggwEUEn3Po2jQGHI7u9ThyMezFE5I8LDGARLqKCSHbT5LCgnLoEEmg+lghl3hQTe/5MG00G6eMV45sB+wtv9LSK2Nzyq+84nzx3DphZrWD3LancZr2xfoH1YCjNaYUNiCS9kJJFENWkb+iyYalKYWCxGFsUYlg+rFI1+JrXRtofaOfn7XYtfI1ygW21iglbVblMvHPh5LSQVkYE4099jgaRcyRAwn0ajODhSYJNrOwIU4GVe0A8dwv0NOTiAEGmJR7kIY6qaApkZJ2PYsm6shjipkr4tZmCpmewwwyOMYpVLCyii0hdOTxSCo/rg9jlMSWJvYcUx3nnlKD4CV/uMzO1g+T3R9kdCJQB5mBSKydjbYOipRVMOb6X/VxNv5XvI+MfEcUjEkMLO9xsahFm5DCCG9akgC5dmiL+n9pQ3CAGCLmXumoEkIyga/Gs0q2csLlB3E7Kq9kgpdjsJr7cfR+ifSWmWanODnCt5y6mE155Cx/jG5BhZsjni9GflD2kmImZgSnekmcO3QKwZC+3pRRkz6dnk3kTJ3aa7QQvSFYl+g1YnthtoeR2CaHwCYQY7cTgAu9EPyNO5FIzvqWaUix+FWdVVxyP6ukhvxOfF9l2CtxuTRYEupWU8QEbuqnIV3v3JbXSbPK3HbuXJ+v5EgxjSaNDQJwsFICzSqMM1yCtuIB0Zc2s4o9DziNwjJcyMlwXBLTLEGheBE+h/B5VllxcT/iv4NujoXBrPLlRRFtV94aCrTW6rFMOFDHLVTRoEfZ2UsVUXhYgi87X3nZI1FXPn5HSakMCzira/KHwrUaWooZoxBcMLPnFAvLVFLqGyFlG0tlq9l6PH3TJLSgDbqauSRybHZvB8IGNA1DXMCJ2upIuls18buqB9YojEx7m2hwMkLVUnN/kEncZGH3Yv4f8Oita0N5y5XQM8AqL7WBxDleEM8QIEDSZg6GmqUg1Oc7pedNdS6HDpWDcuzECr/+lOq+klsvoTTwFHHrdIpFR4HeoaL9GOukxVo9fn2GnzZp4FZI5jGzXF8FxZcpsC6tK+MWh5fgstgP1+LaOkZTYSFNwYNO0L4V5vZ1EGPto/Q1zWzGRkkiE6AMoySJPRVvTSQ+cV+uZNTc4iJtawizY2xJ6rvs+p1Xw9qnepmHyHbz7OLj9fDm7OK3YboFhrN27k5/xM3+Yv8qcqxVgVfF+tbS65o042w19ObNDmib468p7JT7FSRysXHd1qcm3LNKbiYgryRjeDHDZKhcYkyvxn57zJBjvJtNTYaj6c1gMh78mvQjH8evfn15DRbm2EEI1g/JbMpvbyk+jiCOMQgDQ2lKUp9gS+LCNWNcdbQxRHmTu8RC8TOmD3U7/Wj4wdakyIUuSwyXPos1+jhCOUuZVbI9Q6JmWCcPYL+gsUhNc7aIXQMuylblJRSzSC9QTDUDu1Ev7R7KGaVe70C6Pi8gni/inxEdIh6UDS66PL5CSUlfQDRd8ZeT+yDLdyTr9wIiqeq+nMaZrrLRJn2gaxwWCZUvyBOyXw7yVs3p3PbPMIuq0tiU9UmXGjPh3ere3Z6LKZW8kFcvSNE1WkKilkNBnLRnSQGVAh2qvSziCWXSuMevmtwSZtOBetUhPf+Ury/Il0FiJ1dFop0U93rMAvItRWlvpN7YKUwipcmCszPRH5wBFemucchP/FWoY5Hi/AC9KVSf9wSWZVVRFxvkUlXJ0zj/bEX/1Ko4FteSoF8AVG06KDQNyyjwoHRtbmIimzO5Mdme2VL1yTFms+IoofEjZafY8d8KE95oe7M+ht9sS67TeBfpeaGAFW8vQ1qSShuSeL2P4Sx/pc96uTrVPgrWpCYkkrh8107cD1Yzj+OJnWl0BCnhgruXSpV65b2svX6Js+Q/CNSRfije+Ksaxl6IPSjJQhzszSOQEHrXIIgT6fu99NL30MUi4h4WvHSpRkMAWUSUimZpVvnl/R7g55ZSLl/+0mWhQFtav0zUQ8Mw3u/Bz+KVoQoyW5T/Cw): note that `resetDrawCommands()` shouldn't be called at any time a picked feature is being colored. In fact, the only time it needs to call `resetDrawCommands()` in that Sandcastle is for toggling between feature ID labels and custom shaders.

While refactoring this, I also included a fix that closes #10625. Here's the [sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=tVZtb9s2EP4rhD/Zg0NLfo+bBkuTNO3QYEHsdcCmYWCks0WEIg2ScpwN/u87kZJsJ87WpYhhSKTuePfc3cMjYyWNJSsOD6DJeyLhgZyD4XlGv7pvzagRu/m5kpZxCTpqtMnfkSTEpCoXyZnkGbMwIVbn0I7kpvUukpH0FmksVHxP41xrkHbGM0Afpf2fcsGZvMC1dK5V9tmo8TAIm4XlqNENuuFRGB4Fx7NuMOmOJr0RDcJhMOz3R4Nefzwc9497o9+iRiS9v06HXKsEhIlk7ELK3Azd/V5YdIAJsbC2EzTvIZAPTAilJEbkxbgQBMSoMs9lbLmSpNmq1mLATujcNKtvBVhKO/ifsmwpAONhHe+7472UTvZndCHuarfFLxxU4yKe4r1xUv98An96z6WEhJynTLPYupq8YQTXrEL/Jw6fQQ/+B/ILxKvIucqWGozBEByWt4LvvG2dVeFwcT/TOfJyIez81aH8IgW35INavwr9i5jRoLNcDyqUJPim/CoJb8sG52J3/H1cvtIqlwn5CimPxZtB915KJ/uz7+LzZ2w1TMZI5NcS4RvAo+naz97kOYH/LfV/uEbpu2O6fNLtPwFLuFzccBunt0p4YKXsmtmUWnWLGkyaZjgOWs5o4J++BXu7c76G5KNmGcw06s6VzrYdv/5kKB4LTHg99bFecwV4vjCrdHkKSKVtWsYXNR7A2G3DrzO7m81cizZJgS9SW+bbw1oqw51yjeWcaYsjJnvu9LmAhQYwZTmOwm6PBqN+fxgel8nt92kwCHqjYFh+8F6KscdDykOUmhijoEvNM3S5AkM1ZGoFZ5hTX5Od8wnxvLSKJUmJpqpCscCBvcKqN2s2YcyT4lGzwFnGmmm+nhxIffqk0rsF2KFjlbIdciFpdmal5Ush+NIontBfr6bj/o7CAS7U5NyC5Xh/yLMb1BVT/hfeI8LueCtl60I6RbKgpBvgr5RtWlXqkRqyDJoa+yhgn9j+1buYcQHTQlxlLlZC6WIP68Uda3YHA+yw/k8HrZJ0m6q23rzG1D3eYAW4AWpTkM3t/nYa9Savrj8YvGbIdnV/ZuvkPkvtS/uQycVuSQ5vx/6g1f4vnaNwT8lHc1c0QfQ1XaaggWrUzQ35gWxbiB9UOajW4Y0DGervfRiFo2rB7pqRGO5yskfbWvkLiujt5c3l2awu5Ls605vC0ZTJJGbGYmdGwzOlxB3T1yBzn2Lj4TTajRNX7dPK6488W2K/KLZCE9uoBWyjeLk0nTs86sHS2JiqJ550dpeeJHxFePL+wE2XxIIZg5J5Lhw9o8bpSQf1ny0VytXt5xVowR4LtTQ8/eI/UkpPOjg9vNL6CJ9Y/gc) to demonstrate that it works (on `main` it crashes).

Finally, to match `Cesium3DTileset`'s API I added `makeStyleDirty()`, which forces the `Model` to reapply its style. This is to account for changes like so:
```js
model.style = ....
style.color = // new color function here
```

Without `makeStyleDirty()`, the changes won't take effect. This behavior is the same for `Cesium3DTileset`.

**TODO**: write unit tests for the affected files

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @j9liu!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/model-style-commands-needed/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/main/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.

File: Source/Scene/Model/ModelDrawCommand.js [hunk 1]
```diff
@@ -56,25 +56,22 @@ function ModelDrawCommand(options) {
...
+  // not replaced. When this changes, we need to derive new opaque commands
+  // in initialize().
   //
-  // As of now, a style can't change an originally translucent feature to opaque
-  // since the style's alpha is modulated, not a replacement. When this changes,
-  // we need to derive new opaque commands in initialize().
-  const needsTranslucentCommand =
-    hasOpaqueAndTranslucentFeatures && !isTranslucent;
+  // Silhouettes for primitives with both opaque and translucent features
+  // are not yet supported.
```
Comment (j9liu) [inline Source/Scene/Model/ModelDrawCommand.js:68]: Note: this was implicit in the design decisions in #10697. We chose not to derive translucent silhouette commands because it was going to get complicated, and we figured that the case wouldn't happen frequently enough to be worth the complexity. We can always add support later, though we would have to redesign the derived commands system to handle it.

**Comment by j9liu** [comment]
@ptrgags this is ready for review!

**Comment by j9liu** [comment]
To confirm there was a performance improvement, I did some profiling:

I tested picking with `b3dm`s with old `Model` (1.96) vs. `ModelExperimental` (1.96) vs. new `Model` (this branch). For this test I used this [modified 3D Tiles Interactivity Sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=1Vl7bxu5Ef8qrHvArXoyLVlyLMt2UD/kWqgfOltJmqsKm9qlpIVX5ILL9SOBvnuHr12uHkl6yD81YEgkZ+Y3HHJeVMhZJtFzTF+oQMeI0Rd0RrM4n+OPei4YbYV6fMaZJDGjYrRVR19HDCFJhYCZgeDPcURF1zGGghJJP3GRRENDEtTqI7aoHY7YiIUaMAspo4BngLEewnI8QcFf9ACncfg04FksY87u8zTlQtKoZpBfYhbxF0wSKiQoOJzFGRoL/pLBHiJOM8Q4QBgm5AvCoy2lxUIpYmCmCR9THNFUzoY0kydTUDeTVm9QUIqcenorfa95RBNY0qqIeDqTZwlgnIQKoYtGW4QBPpgALKVI5nEUJXSJZgYm0+sLLd2a7onx8InnEktBwqegQPNNJzlPxkQdVsTDfE6ZxFMqewlVX0/f+hFYxNKY3S7LJmmavJ2CCWM2zUqMupPsg9mtgNIZANqTEfEcrPlMM0yiKPCuzBUZ0+SMJwnV+wxqRtTODrqnoPiMopgBJ0lQSOZUEG1OgEUJ50+ISHRN2IxISQp8S+/OD3SwUGcE7kMWE9bCE8Hn53QqKM0CZe/t/TZuNDudZqux22k0dtsdfQztBn530Gy2W63WfrPd2W3q2f291ogpNSt4tyIGYxIL6e3wkhJltkEsw9kdbHQFfLeJd/c7+wed/c7uQavT2tMo2zDdarcOGnt7jc7+bvudAW/gxn7z3cFe8wDUPei0m3tGF2NnYyOcUalcMdDXLYI7GjNibtGScbRIXmreXbMbTUNZNBSEZRMu5oXXXhMp4tc27p/3bob94efSY+H4rjiJ9PndfD5D4zxO9N1BMk4oqIeLq2nGVZOZj9b50CyafeQiKZD7nN3RjOcipNqcJxmQwTWGo2m3isix9u5ZQLXudMnkW0I3a3Cvlo0OcypJ13ixNmwo4tS556+ndpPol6+n/ZsFmpEMzahydpi51F8W+Ffr4Yvl8DYjDFx+KaDeQ2Ck7D4lIe09w4FcGqLAxsCQsGeSGSmWX519n6W5NHEjmORMf0HBnD9rf7cB0aBOIO7mgpaOChGnoMSpvSYKASEdaa1iEZ1AYI8Cy1+rOaMICmOm6XXIdEAktJ5RBA+8HAcLEEd7fFyJjAWGmyoUrbt9GEUXiCYZXRWVCp5C+I9p5gmD68HkoFj5X2V+4XzuSVPDjSLgxOubTnb4llJ81//H5fDh7Kp/9s//10NdyVzrT9XksgLAIuJsxl9A3ISArX/QZtf98/Ornm+0wjrfuCcGWKn1/dLB7TZ0+aNiWMe1ycAGZcnChajSxj4KnwqSzuKwmrvcrI54RTLzZB1WJdnYc4wef/nqS8VmAUt+Eb+CMru1BZo/HpqD9fxLZXAdMgsNwVvs3rqlNerlqqSvsmtxvWl1qqdQnEwFz1nU1QWStzyBMlEF0GY7fUVzznimTtjGSfM3gxz1RVWTKjFNY1YkgsulBXzVuxh6jM/Kq8MVto+VaXx6OxzeXntsUZyRcULPXY13HmdQYYS0i27y+RgccnB73x/2P/Ye+jcX/RuT+wzrwh3Dwt3fyp38frgpPZknFCd8CsVZydA1BZo7YxvSoIRTxZZzIyjuBuVC4DMklE3lDGg9TmwmNRUkeBQkkJBjoGkcwseR5TlEv/0WL7lEKaQq8d/xfw5LOrePRwSJsKRadGG4RuWgJKktHmt+2IG6ovdMkhycuohyXhpeMZxW4fG8pEAKs5L3scrp2BOCqUUo4uDiUQkquoDiLDcEez8UJ5xNY5lHtHRlqJpm4Ht3UBVCQRVUA6BvhtHWleOGQ3cqFJLBQf+8YMu8Rm4RNdZzmjrGXELvGtqwcFYNXn5B5a1Y1QrbWN9xO7JDq8jfoOTdW1YyLYt7vyejSRKnGY8j7Me7IS+Dpc35a9R1ECWIbTgchBlWLKULeyCwZbed8PVURX9JoIcVDD6ZmOrXfLmAyF7pFwib0sDZQ89b62hRy5baxY3VbUhXt5c3pSjlM0xJJm8g280+pEOTDy4EKBtUk9hSwT/PExmrjvBtwCGcBQVE3e6jjnx+rYuxwCR5G/KgLKDLziT1W5KlpqRIQNYG3SVjWHN0K1ZZ2E/YIVBeWKctUkCvMo1//3Byfncy7J893H4wCWSx6vDfOiSnkdUBCTVrY4G7Br6jhgmZp8HqYW77RIP+w+3H3t3D8NOtXd6wWjpIeSt90i9U8CEfvvBB7DStoe1N0qq+rZT7HQJiKVKNqGDKbrr7eo2zEzZN3E1d7bc/QIp8cDlyW0tcjTtaq58B9IcDsjKXoQSXG2Hc1a46nSLwHc8bexRrcIzHVA4DxuYBokQNrEa19bFhdZshxE4abNj+v9b4bMvz2Y80lFwEhXal05rPCrsnnNGpyoo/RlzC3UOdRUTBpv2iym3aCzvlnA5SfZ+pmGKeVMiY5+Y9KMyFgNCQvKEZhL1EhT4auWxVdNPekn12sxRdBDWoKcPd6weUgES9QXHRraQsNWPeId2jhp5CpKg93iDjQMcC+s2gDBB4xIrXybWN+8ZGjrNrnmf0GqTom+eqihGzIUSZY+Ihv5AMCi76HANb1RR1tUGuTVXMumZnqQ3xuPBK07dmEYd6/8eVtYoBDzfyAldh+KWSbgBtFGxNmb44xjL6hE+QkwoZ/uvvUmNLWTT4bm9bkfetDhf0unS70Mb0VFu/vYroilsoy1ifrRAZe9Y3m9PsYw2PFxW0cB0dk3RGgsr0597V1e2nOpRQ73Q2qxdPu+t76dsP972Ha0gDinqrvnWkS+T3Lsv+PZ7r9/FcJAHGO5LOUyjaaLYzzkFDicMsK5vQv7pXZ699HHtdoJiOSdDerSP338Cdkht2Da2nzvXQFnrTYy4iKrYFRN08qy4uVqB1SUYrKqhuc/tFV0xdEJZEq5DbkqddtFeBdUtjLiWfV1ct7tGOb62jKH5GcXS85scQBLk/y2BlkifJffwFyvD3RztAv8KacJ1cbiG2JORNkc2a76/MJMb4aAeG6zmL5/zi8PSaQzZ2gdU7fb/DRLugqZB8gYbtfWmHo1iFLyThuoAYdQocNqQ6JjUuH+tQRCTZHsdMW2BG1Q3urvz0AQqcOBaH9+fR/fe9H8YfqIZcP+wqjp+ghXkR/GH8P4Bc/Z7hhZf1Cqye3bV+a/tph2fe5NYrvvKsB/CXQP8ttf3v/wU) to profile between the three. I waited for all visible tiles to be loaded (with no additional camera movement), then I recorded the performance for 11 seconds, moving my mouse across the buildings at random so that they would toggle the yellow translucent styling.

| Model Version | Result |
| ---------------- | ------- |
| Model (1.96) | picking old model |
| ModelExperimental (1.96) | picking ME |
| new Model (this branch) | picking new model |

**Review by ptrgags — COMMENTED** [review]
@j9liu working nicely, I can confirm in the profiler that `Model.update()` is no longer at the top of the list.

Just a couple small comments about documentation

**Comment by j9liu** [comment]
@ptrgags updated!

**Comment by ptrgags** [comment]
Updates look good, thanks @j9liu!
