### PR TITLE
Incorrect texture coordinate for Wall when there are duplicate positions in input

### LINKED ISSUE #9042: Wall has incorrect texture coordinate
image

```js
var viewer = new Cesium.Viewer("cesiumContainer", { infoBox: false });
var entities = viewer.entities;

entities.add({
  wall: {
    positions: Cesium.Cartesian3.fromDegreesArrayHeights([
      -90.0,
      43.0,
      100000.0,
      -87.5,
      45.0,
      100000.0,
      -85.0,
      43.0,
      100000.0,
      -87.5,
      41.0,
      100000.0,
      -90.0,
      43.0,
      100000.0,
    ]),
    material: new Cesium.CheckerboardMaterialProperty({
      repeat: new Cesium.Cartesian2(20.0, 6.0),
    }),
  },
});

viewer.zoomTo(viewer.entities);
```

### PR DESCRIPTION
**Pull request by baothientran**
Fixes #9042 

The original wall positions input length is used as number of corners to calculate for the texture coordinate. However, after the input is cleaned for duplication, the length is outdated. I use numCorners returned by function `WallGeometryLibrary.computePositions()` to replace it. 

[Sandcastle example for the error](https://sandcastle.cesium.com/#c=lVJLT4NAEP4rE040qUvr24qNWg8eNJpovIiHLUzLxmWXzC7U2vS/u5Su1keMcoD5hu8x7FBzglrgDAlOQOEMRmhEVbCHVS9MgnSFR1pZLhRSEnRhAUJN9Ll+GcCES4Ow7BwnqnZOqKywAo3zak2Z7zhCojxgPMvCRaIAZlzKAaxKgFIb91orM/BTjDhZV3G1wyakiwucEqI5I+LzSxTT3JrwsdUCbB3usV7Xo92dDdDvNddGwz8/oygCpa1IEWyOkFWlFCm3+D4X5Ej4EXfA9j7i+r/F/Yf7rjnq/fFznjrronDDkuDuQDcWOcoxfUYaa07Z9ZpwS7pEsvNw4S0JS+T2s9Cf/Xa43YTBPuv5pGVbLN19tXu3/Xbdr1oX9zr8svzOcdANYmPnEoc+8VQUpSYLFcmQschiUUo3nonGlZvXstSYxrmhxtGmNM5EDSI7+eHXhFRyY9ybSSXlnXjFJBjGkeN/k0rNM6GmNzWS5POGlveHV22TMRZHDv6stFrLMacvzm8)

@hpinkos Can you please take a look at it? Please let me know if I should fix anything

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @baothientran!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/Wall-incorrect-uv/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

File: Specs/Core/WallGeometrySpec.js [hunk 1]
```diff
@@ -448,6 +448,48 @@ describe("Core/WallGeometry", function () {
...
 
+  it("creates correct texture coordinates when there are duplicate wall positions", function () {
+    var w = WallGeometry.createGeometry(
+      new WallGeometry({
+        vertexFormat: VertexFormat.ALL,
+        positions: Cartesian3.fromDegreesArrayHeights([
+          49.0,
+          18.0,
+          1000.0,
+          50.0,
```
Comment (baothientran) [inline Specs/Core/WallGeometrySpec.js:459]: There is a duplicate at the 2nd position in this test

**Comment by hpinkos** [comment]
Thanks @baothientran!
