### PR TITLE
Fix the transformation of plane's normal

### LINKED ISSUE #9109: Transforming a plane with a matrix doesn't produce correct normal
When transforming a plane with a matrix, [the plane's normal is currently multiplied with the transform matrix itself](https://github.com/CesiumGS/cesium/blob/fa2edd6d0f77d2977e957a9334ef42a880a83897/Source/Core/Plane.js#L210). However, the transform matrix should be converted to normal matrix before multiplying with normal. This is the [sandcastle's example(Notice the angle printed out on the console)](https://sandcastle.cesium.com/#c=7VZNj9sgEP0rKCdH8uJE3Z42WXWba7u70lZ78oXYOIuKIQKcbFr1v3eA4K84cSq1t/pgGZiZ92bmAd4RhXaM7qlCSyToHq2oZlWJX91clE4yN15JYQgTVKWT6V0qUlFUIjNMClSwd5p/U0ToQqrymRNBo619x8iE2RgpqitupigVP1OB0A5QBSwQ/pUYxd4B+4jrx7fY+W6lplFvgYkdVTDdCt6ifbSKptMz03cBvvZ/dDxOGZRAmG354fPhWTJhHvQrzYxUUZt3jFyq2M91IFdEGfgi4kNAPVk4urEfrWwej5F6E77oPebPUjPXg+VA7Ib+S0Y4UVGX6Y0f5kwbIjJ6HfUzpWn34oTcwFRIRlFTKRGCO+ngQsnSBfV5R5fihVodxQVRf9nASYIyRYmhSCq2YQKa65L1K1IUTJWICGneqHJQiGkEVYRxzwOjR2lYRsF6w6k1m6Wi0e5g3ZueDld0jmcxmtkXfIFKbSGufC60yJJylLu72G/H0HNADbY+z65xK+asJtny6ZTsnGeT3s28cc1ZUQxWS1draGdmIk8o7oDEYxn7tgzFzaWJLGh3g1o/EICWnGIuN5Hz92oEadS6GlAC2jPzBm0XN5VgzkbDrqKodDvCudcagQzQDIYHVEpFPVNnfe6ss5q3m/ScZD7act46ycycZs6dbB7LdA7jBs5vsHo1nNItavGAdka67AnZd2hKDfAUNDZyenQIBB2MdL4GeeiK8k+grpbauHp7OcfD/C6CXKPlbmfHRe10CRd0S9rNSdjS696eayeyuXCz/03N/HO9/NfKuFYm8WShzYHTe3sffWLlViqDKsUjjBNDS+g7QCTrKvtODc60tk6LJLgscrZDLF8O/C6ijBOtYaWoOH+BezGd3C8SsO+4cUlyJjZP8G/HyQFMLI3F2/z+i1/AGC8SGFrQvq+Rkq+JasX9DQ)

This also happens in the `czm_transformPlane()` glsl function

Another explanation from stack overflow:
https://stackoverflow.com/questions/7685495/transforming-a-3d-plane-using-a-4x4-matrix

### PR DESCRIPTION
**Pull request by baothientran**
Fixes #9109

This PR will convert the transformation matrix to a normal matrix before multiplying with the plane as vec4. Most of the fix happens in glsl czm_transformPlane() function and Cesium.Plane.transform(). 

I also see gltf_clippingPlanesMatrix is used for IBL as it assumes the matrix stores the reference frame components. This may no longer be true, so I change it to a different uniform

@IanLilleyT Can you please take a look at it? Please let me know if I should fix anything.

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @baothientran!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/revised-plane-transform/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

File: Specs/Scene/PointCloud3DTileContentSpec.js [hunk 1]
```diff
@@ -1155,7 +1155,7 @@ describe(
           tileset.clippingPlanes = new ClippingPlaneCollection({
             planes: [
               new ClippingPlane(Cartesian3.UNIT_Z, -10.0),
-              new ClippingPlane(Cartesian3.UNIT_X, 0.0),
+              new ClippingPlane(Cartesian3.UNIT_X, 1.0),
```
Comment (baothientran) [inline Specs/Scene/PointCloud3DTileContentSpec.js:1158]: This test have the clipping plane close to the center. It can generate a different color. I move it off a little bit. This is the [sandcastle example](http://localhost:8080/Apps/Sandcastle/index.html#c=nVRtb9owEP4rJ740qMyhq/qF0modbadJXYeATtPGNJnkgOscO7IdWjrx33d5o6FvHyaCHNt3z12e57HDcGhIexgok8UwW8PQmrmAIXq0cKYU6g4MjMqSGUm40bRC68ivYWRmxlPk4ErOBIwjqTXpRQ5wpvBW6tgamFgTRUYR8BS+SI8EAzKRtIpQTPVKWlgR3nGhE9B4BwN0lCXiW7EWTFtRMR8Y7SVptNNWB/5ONcBCmRn2YC6Vw85Ub9rHU13CeVLo0O/ilcPh+aTcDAqMzKoeTFtChOUzTjFy4bn0MtyJL+kp2Gm8jj59DKta4tYZza1t+6jXLcp4zWwm5FD4JepgnunIk9FBu2ihDowUpSmTN1RSo3vSe3OPdVBYIhQAAGmR0oOf5RReTQ3qRWk9v0l9KG6uP09+/+jAu4Ou6LY7/4vwvQON/F/VmJgYFUtu6b5Xw02s1G5ubOIESuevjfXLm3RiLuke40srEwzqJmpqZibTMXcwTpdoUUSo2ZZlUF0x08xH3ekIFzxzj94AKFSBymjCMQSK1FJCnr3shIzjoKq2E/hgTDIxu1v5n/uHQLHFiIXqHvPQf0VIwWdn4Zccsr/fhkqwiLszCoUyi+CVtAVblNplRYC8VKHyBRuLz91JjcTiGz6J/Lm9t+naKuvXKZ+aveEj2t52ryjRe8QGiClB7Uo2m56o5X8fHIluB46a3mHd+ZRbkmorOnvWWDG6OBd35JdnKl3KoCsOmjlV7TfpaISbzCsqEmyGz9eLgs/L13Gb8mVT0VupjTkdVNmhQXepwmZ7tvNfq9PqO79WeFpjfqAkZTPnd0rAV4nHhCGYpXCWRX/yL3KulrMfNlP7Ma2A4pMXrjqIlHSOd+aZUmN6wGnrtB9y/LNUZWSu+Ve+mZVc52HLg9OrclEI0Q95+nKmN0bNpH2C/A8) for the test

**Comment by IanLilleyT** [comment]
@baothientran I made a few changes. Some are based on your changes, and some are completely new.

1) Changed the names from `transposeInverse` to `inverseTranspose`. Only doing this because it's the more standard naming convention. Behavior is identical.

2) Changed `clippingPlanesOriginMatrix` to `referenceMatrix` in `Model.js`, and deriving `_clippingPlaneModelViewMatrix` and `_iblReferenceFrameMatrix` based on it. 

3) I noticed that the ibl reference matrix had scale built in, because it was using `clippingPlanesOriginMatrix` without removing the scale. This was a bug waiting to happen, but luckily the shader was normalizing the result after applying the ibl matrix. By the way, I've been testing [this sandcastle](http://localhost:8080/Apps/Sandcastle/index.html#c=tRlpd9u48a+w/hI6K1O8D9lJm9jJxm3SuI6StF3lORAJSagpgg8Ebat9+e8dADxAHXF2324OhxgM5p7BDHKHmHFH8D1mxjOjwPfGOa5IvbY+SZg5O0rl+pwWHJECs9nRyPjfrDAMUizoS/owMRYor/BIgCqc45QTWlwWGUkRp2ywu6J1nr0oyBpxPDE4qxW8ZPQ/6tgVSW8x07Y4Zgy4XjF6RzKx0wiXMgw0PlOWZ1OFYh7DgW/Hp7NiVih1LPzAcZGZzREFVAvvYkpyXF0WVQmMKXtHHkjRnAVzLHM6x2CNhk6V4gJbEggo8l8rwyVfTXHFXyyBecUbKeCQkF1San8LiiWtiFAQ9htxzhHj8IUKz1owur7AS4ZxZQqlTxzXs+zI90MnkVbwfcsObC+yQ7n0bNuyZ1JeQXuFUUaKJZAGcAMrCU9XAwijeT4ArMoth79RdK7E0WvANhvCI0VtJEm0TCkjGAJiqNOUoaJaULaurNUWsX/U4C9WALpUsbWH1AckmTXWnxXjp4rBmmY4f4c4Iw89A7X2pcUks1xK0BO/pkqmDynK8S4nTWq51rTv/WG6YKSR0f88VtI9Hff+3Cvdd9Sf0tfkAWevGVrjRwygGKSbnBQQ8ddAp66Ax4ltBa0rJexdnXNS5kTmrSPdqrYrjktxwnMb/DQnZSmkyVGBxc4vX041NV4VnPDN+QBp6+Q7wPtYKF/LfG72cYHmOc76qO+ISgdsCSaovZ+LVJdCzI4kpqgns6O5l63VV1nwSn2RDtaUgdlRK7jITCGUCGlZjIb2mmytVZkRmp3TuuATZSMJ7aWdaN9QSqTYjWdvC5re0ppbnKH01uy49yWDU5rPkXBFRtN6DVFmLTF/lWPx+XJzmUEhbXBmR+LYNmVUlvnmJcgM5q56DqOW8vE+eYQCgs/7eYXZnfCFfhJK98AKwFgeqOp5lTIyx+aiLmTdNUzIhE8or/GxMqexG4AlYhV+nVPEex7WEEvIKM7WZQYJqSLJVMBvv0n+3mW/SnbhEAB+aBJhr+Q96VZqspCk1Kk/PXumgqQjanSJ1SKdthsH08hieE3v8AsopscddkrXZb1lHjDQb7eSFra/xkqDPN1rox6jlTKlRUVzbOV0aW7vir/jsYTClanI9jgdiixRzfb++tsfGhn7vxXDxs2HLokKc3UNaMV6pFiPdM4NvnmsqK571TvKHRc9lrt6K9qDrW6hvYaFj2VgkGHhVY0SzmQQSGqdo4bJo5wFl4phinNEXOGn8M/ZVlW3clws+Qq2fvppkAdSBDg1RP+FfGk8KvetjFQcFalEHCb+053rRtkAKuRA7K2oViK011HT3Qx8tLKmn9/fXF0aY5VYkuz+q+qQCdS5HZUR9GhCEwLCa9xPe4yMsIPR14Y64FgP3Q3WQjYAkcKDuUzJSC8fivPzgZZXlzfvP726vgFttVrSUj/pybcMng6g3x6j/n2i335YODCWt4fWrnxAX34MOey2tQV0Qign/8UmoI/E4ePTQX2+akJT94Puf1PjO+qq52PhqRBbVodLM8oysxWiK29DlLKuVls4u3EvJ5Ehbb3iNCY9KMd39D+HxlHNRaZeshXdbhTK8ALGsmzAszXWn/UTLXCyXSgvL179fXo5/VdjY5wt8WeS8dXEcKEF7oEgD+1HMLmyPr+5nL5qcGrRIbYaXOMlrEQntt1DthRV7zhpP0Zdad13RX4bdN4fmWj8ZkeWNYY/H9C6zPEF4kjdPtX4Ct0XzU+Y2+azo65fvSOMFqIne4fKj9dvJZUV52U1GY/TZrak6zGq4PaoxrcEMXQT3qCFmC8oLW7c2xsyz61b/iCJwrwyNqYrUumkjTUqjXtUicEWaFbQINeVmNB+phRS8EllvCY5kpjN6GsZU9piGxtaw3x1X0wkccc4MS5gBVdzZvAV7s8yuENQhQ2zlX9J+KqeS/mXktN40eCOG9zq2JJEXSB6XRfG13S9xIVxcsI3JX4GSsEnTLY53Twbl1AfxpyOoQEBXxjdGqb3JbZWGftqGe9BICZKM0z0lYEYNmA4oEZVlyWFOpBZQy4rnJdfZSVHMIzSUoR2pSTyQKIpusVSRcDGDLIqg0DAiwVJxdQG9Atlgb9N/2mAZlgCWrusDZi+VWj+9YMBxq9WYDVjjnN6b7XB89a2D9Z9EXe25US2HwROYMee47vuqIGGnhM4ApbYbjOUAzQJkzCMQtuNkyj0+on8rXPjfJcPDHN2GAaB7cLxOPFib9SCXdeOYzsIIj+0/bjhZEdx7AW2nbh+6LiRzukxhWwgHvp2EvlRHCROS9APIsf3bCAZR4HXQkPPT+LEBtah6wQ6m8f1AXJh4IWe57ix06sT+okdOl4E9gt6cGA7ceLbPljBdjU+7o37KCMg5LlRHCZOFCcaxQh+JUHkJkkc9uDQBwF83w882xtych6znO/5gR8kID0o5neWA5e7QWI7tu8EUQsNwIoAikLYdnQ29qP62A74B465ke90/rHBimHoxa7nOEHYQSMXYs2OwUmhE+psHvcPRHNoxxBYth36vSf80Et8D4Ir8SM76u0WBaGbgDshSmM9EtzHHWT7CdgLnONA3PWcAB4lYeyEoR9HvUox5Brkm2OHiRv3jAaZD30gpO5IJpb4KT/FF8SL/Cm/BdSVX+6X0623mlPtyhYlQw44Zs3y5n7ee40fN71nd4FvvwmWjKyht79r2olBJ6RGKPFS9XPOF2bXWAHPSXeLjQYjZHuz6wNLiwCTFSnIul5fkQeYgqCtmhgQI31fNBB9crjhaLo22SPoEw8YINtcgbikwnKIhKJaaPOjxBr02SncLQz1NlHrxmZCYuPflK4NThUH7SAtuHhMlE9XA4PC1Ipx8aFEKT6X1M47VK13hGOt2tChQA8oe9k1elBCWnMY68U7yocSridsqQ5x1MgLLqkrDg4qMGLaXNuwsRozC9Ev+qmIARf1AqepAbEpVdjqp9aqF9283FxRUnBz4GNrn3P3iq3IdzgHppVhuzt8D9Y7fU5Fx4yKynQ98aapHWgfi/ejn7gaemPCnNLbF71ihyUdvCnDAIJ3H5XBsK58Y9X1GPDp3lXNA43rceeW5vVBGJDAoP8GsTUtSHo+LCZ6bTkdHsRpnSP2atAniiM7nWPzEiAzhYo26B7yRksXzBhlXbrcw8wCfQiCAOPNVv+UIHvbvii1tUFpdTQ6Oqv4JsfPW/P+haxFdyUKiQndL8fQ/ULtqsbzOr3F3Eqr7iHubKwfPcvInUGyZ3v+SwfKB7S8sLOoc1lcZkfPz8aAv3NUyAn+e3+HWY42Am3lPH+rgJZlnY1huf9k9/zZaXLGReffLQVgTrONBhAgNlgLSPa8zcyzMSx2t4cQgJFC9LCyy50dMRGIoDNkOqzEsCwW6AEW6ls8GsBCNDWwymCwOJmDAwF0J17Qdl6XDQn+KB9uJsYTyeyJpud+MTh+4IIZWBtWwY9w2qF5QH81WcvXzd/BQk5vHrihO/McsE3/sPpH2kV/Gf4xm8i3wN/BGk1UKIO4PxYv+ivmH2cT/R34MZsAQM8rWA4yD9Zaaur5/H8) to make sure scale is working properly.

Let me know if these changes seem good to you.

File: Specs/Scene/PointCloud3DTileContentSpec.js (hunk 1 above)
Comment (IanLilleyT) [reply Specs/Scene/PointCloud3DTileContentSpec.js:1158]: Hm, not sure I understand what to look out for here

**Comment by baothientran** [comment]
@IanLilleyT The change looks good to me. This will make it less confusing about why using clipping plane matrix for IBL as before

File: Specs/Scene/PointCloud3DTileContentSpec.js (hunk 1 above)
Comment (baothientran) [reply Specs/Scene/PointCloud3DTileContentSpec.js:1158]: The test fails on my machine if the distance is 0.0. I tried on Sandcastle and it seems to work the same.

**Comment by lilleyse** [comment]
@IanLilleyT and I did a final pass on the code and added more documentation and some code cleanup. We tested this using @IanLilleyT's sandcastle above and all the other clipping plane sandcastles. During testing we noticed a bug with `Model.js` shader caching and opened an issue here: https://github.com/CesiumGS/cesium/issues/9141. The sandcastle in that issue actually crashes in master so this PR improved the situation a little bit. No need to look into right now.

**Comment by IanLilleyT** [comment]
Merged. Thanks @baothientran !
