### PR TITLE
Fix require for Node.js (Fixes #8559)

### LINKED ISSUE #8559: Regression: Cesium.sampleTerrain no longer usable from Node.js
It looks like the ability to use xhr from Node.js broke in Cesium at some point. As a resultit is not possible to use ```Cesium.createWorldTerrain``` nor ```Cesium.sampleTerrain``` from a Node.js application any longer.

The error I see is the following:

```
TypeError: nodeRequire is not a function
    at loadWithHttpRequest (/Users/morin_ricardo/Projects/sampleterrain/node_modules/cesium/Source/Core/Resource.js:1892:19)
    at Object._34e‍.r.Resource._Implementations.loadWithXhr (/Users/morin_ricardo/Projects/sampleterrain/node_modules/cesium/Source/Core/Resource.js:1945:13)
    at Request.request.requestFunction (/Users/morin_ricardo/Projects/sampleterrain/node_modules/cesium/Source/Core/Resource.js:1298:49)
    at startRequest (/Users/morin_ricardo/Projects/sampleterrain/node_modules/cesium/Source/Core/RequestScheduler.js:195:17)
    at Function._34e‍.r.RequestScheduler.request (/Users/morin_ricardo/Projects/sampleterrain/node_modules/cesium/Source/Core/RequestScheduler.js:338:20)
    at Resource._34e‍.r.Resource._makeRequest (/Users/morin_ricardo/Projects/sampleterrain/node_modules/cesium/Source/Core/Resource.js:1307:40)
    at Resource._34e‍.r.Resource.fetch (/Users/morin_ricardo/Projects/sampleterrain/node_modules/cesium/Source/Core/Resource.js:1414:21)
    at Resource._34e‍.r.Resource.fetchJson (/Users/morin_ricardo/Projects/sampleterrain/node_modules/cesium/Source/Core/Resource.js:1091:28)
    at Function._34e‍.r.IonResource.fromAssetId (/Users/morin_ricardo/Projects/sampleterrain/node_modules/cesium/Source/Core/IonResource.js:98:33)
    at Proxy.createWorldTerrain (/Users/morin_ricardo/Projects/sampleterrain/node_modules/cesium/Source/Core/createWorldTerrain.js:37:30)
```
The issue is that ```global.require``` is undefined in ```Resource.js```. At some point in one of the releases in the past year it got messed up.

Replacing line [1905](https://github.com/AnalyticalGraphicsInc/cesium/blob/83e6fb9ffffc73287d17a49ec403bfad1d5780d9/Source/Core/Resource.js#L1905)

```
var nodeRequire = global.require; // eslint-disable-line
```

with

```
var nodeRequire = global.require ? global.require : require; // eslint-disable-line
```
will fix my issue, however, perhaps it would be better to understand why/how global.require in Node.js ended up not being assigned (because it was working a while back).

Please let me know if you want me to send you a PR with the fix above.

Thank you,

Ricardo

Related to: #6463

### PR DESCRIPTION
**Pull request by jimmyangel**

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thank you so much for the pull request @jimmyangel! I noticed this is your first pull request and I wanted to say welcome to the Cesium community!

The [Pull Request Guidelines](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CONTRIBUTING.md#pull-request-guidelines) is a handy reference for making sure your PR gets accepted quickly, so make sure to skim that.

* :x: Missing `CONTRIBUTORS.md` entry.
    * Please add yourself to the [contributors](https://github.com/jimmyangel/cesium/blob/master/CONTRIBUTORS.md) file!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/AnalyticalGraphicsInc/cesium/blob/master/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

File: Source/Core/Resource.js [hunk 1]
```diff
@@ -1902,7 +1902,7 @@ import TrustedServers from './TrustedServers.js';
 
         // Specifically use the Node version of require to avoid conflicts with the global
         // require defined in the built version of Cesium.
-        var nodeRequire = global.require; // eslint-disable-line
+        var nodeRequire = global.require ? global.require : require; // eslint-disable-line
```
Comment (mramato) [inline Source/Core/Resource.js]: Now that we use ES6, you can just remove the `nodeRequire` variable and comment above it and just replace it with `require` directly in this function.

This will most likely have to all change again for Node 13, but there are bigger issues that need to be addressed there too.

**Comment by jimmyangel** [comment]
Ok, I will try that later today or sometime tomorrow.

Thank you,

Ricardo

**Comment by jimmyangel** [comment]
Hi @mramato, I made the change but there is a conflict in the contributors file :)

Thanks,

Ricardo

**Comment by mramato** [comment]
@jimmyangel I could have sworn I merged this already, but thanks again for the PR.  It will be part of the CesiumJS release on Monday.
