### PR TITLE
Fix ability to "unset" material image

### LINKED ISSUE #9385: Unable to unset image uniform for Material
It seems not possible to "unset" the `image` uniform for a `Material`.

Just as I can create a `Material` with `image: undefined`, I expect I can set `image = undefined` to achieve the same state.
However, it seems setting `image = Cesium.Material.DefaultImageId` (`'czm_defaultImage'`) does not work _either_; nothing can achieve this, the only work-around is to create a new `Material` (and destroy the old one).

See the following demo ([paste into Sandcastle](https://sandcastle.cesium.com/)):

```javascript
var viewer = new Cesium.Viewer("cesiumContainer");
var scene = viewer.scene;
var rectangle = scene.primitives.add(
  new Cesium.Primitive({
    geometryInstances: new Cesium.GeometryInstance({
      geometry: new Cesium.RectangleGeometry({
        rectangle: Cesium.Rectangle.fromDegrees(
          -120.0,
          20.0,
          -60.0,
          40.0
        ),
        vertexFormat: Cesium.EllipsoidSurfaceAppearance.VERTEX_FORMAT,
      }),
    }),
    appearance: new Cesium.MaterialAppearance({
      flat: true,
      material: Cesium.Material.fromType(Cesium.Material.ImageType, {
        // image: '../images/Cesium_Logo_Color.jpg',
        // image: '../images/checkerboard.png',
        image: undefined,
        color: Cesium.Color.RED.withAlpha(0.5),
      }),
    }),
  })
);

Sandcastle.addToolbarButton('"Cesium_Logo_Color.jpg"', function() {
  rectangle.appearance.material.uniforms.image = '../images/Cesium_Logo_Color.jpg';
});
Sandcastle.addToolbarButton('undefined', function() {
  rectangle.appearance.material.uniforms.image = undefined;
});
Sandcastle.addToolbarButton('Cesium.Material.DefaultImageId', function() {
  rectangle.appearance.material.uniforms.image = Cesium.Material.DefaultImageId;
});
Sandcastle.addToolbarButton('"czm_defaultImage"', function() {
  rectangle.appearance.material.uniforms.image = 'czm_defaultImage';
});
Sandcastle.addToolbarButton('""', function() {
  rectangle.appearance.material.uniforms.image = '';
});
Sandcastle.addToolbarButton('"does_not_exist"', function() {
  rectangle.appearance.material.uniforms.image = 'does_not_exist';
});
Sandcastle.addToolbarButton('"checkerboard.png"', function() {
  rectangle.appearance.material.uniforms.image = '../images/checkerboard.png';
});
```

### PR DESCRIPTION
**Pull request by j9liu**
Will fix #9385. Not complete, but I had some questions about [this block of code.](https://github.com/CesiumGS/cesium/blob/master/Source/Scene/Material.js#L856-L873)

1. I added something to the material update function (which comes from `createTexture2DUpdateFunction`) that can handle when the value of an image is undefined. However, I'm unclear about the intended behavior of this function when it has no texture. It seems that if a texture is not defined, it wants to define some default texture anyway -- is that what we want?
2. Regarding `"czm_defaultImage"`: is this default image being created anywhere? The function just returns early if `uniformValue === Material.DefaultImageId`, so I'm not sure if the `texture` property is actually being set.

I'm still addressing a bug where if you alternate between `czm_defaultImage` and `undefined`, some random image appears -- not sure what it is.

cc: @lilleyse @ebogo1

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @j9liu!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/unset-material-image/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

**Comment by j9liu** [comment]
>I'm still addressing a bug where if you alternate between czm_defaultImage and undefined, some random image appears -- not sure what it is.

The most recent change should have taken care of this. However, the image appears when toggling between `undefined` and either the "does_not_exist" or empty quote options.

I'm currently writing tests for the changes to `Material`, but I ran into some concerns. When I declare this `Material` in a test:
```
var material = Material.fromType(Material.ImageType, {
        image: "./Data/Images/Green.png",
        color: Color.WHITE,
      });
```
it will render the color white even though `"./Data/Images/Green.png"` should set the value to `[0, 255, 0, 255]`.
I went back to the example Sandcastle in the original issue, and changed the `image` property of the material so that it began with the Cesium logo displayed. But for the first few frames of rendering the rectangle was blank, and after three frames it finally showed the image. The logic in the `Material.prototype.update` calls its `updateFunctions` *after* dealing with `loadedImages`, so this is probably the issue -- I'm looking into it.
- Even if I rearrange the order of this, though, what if `Resource.fetchImage` just takes a long time? Maybe I need to write my unit tests in a way that account for this?

Also, not related to this issue / PR, but the `"does not destroy default material"` test in `MaterialSpec` has no expectations -- this seems like a mistake?

**Comment by j9liu** [comment]
@lilleyse - I think this PR is ready for review. I put the changes under **1.84** in `CHANGES.md` because I figure we'll merge this after the release today.

Sorry about the 20+ commits; they happened when I was `git pull`-ing from `master`. If there's any way I can avoid that in the future let me know!

File: Source/Scene/Material.js [hunk 1]
```diff
@@ -895,12 +913,18 @@ function createTexture2DUpdateFunction(uniformId) {
...
+        when(
+          promise,
+          function (image) {
+            material._loadedImages.push({
+              id: uniformId,
+              image: image,
+            });
+          },
+          function () {
+            material._textures[uniformId] = material._defaultTexture;
```
Comment (lilleyse) [inline Source/Scene/Material.js:925]: Double checking here - how does this interact with the code above? Does it recognize that the texture changed and destroy the previous texture? Is there a way to fit this cleanly into that system?

File: Specs/Scene/MaterialSpec.js [hunk 2]
```diff
@@ -655,6 +655,206 @@ describe(
...
+          });
+        })
+        .then(function () {
+          material.uniforms.image = Material.DefaultImageId;
+        })
+        .then(function () {
+          renderMaterial(material, true, function (rgba) {
+            expect(rgba).toEqual([255, 255, 255, 255]);
+          });
+        });
```
Comment (lilleyse) [inline Specs/Scene/MaterialSpec.js:779]: These three `.then` functions can be collapsed into a single function since there's no asynchronous code within them.

Double check this for the other added tests.

```suggestion
        .then(function () {
          renderMaterial(material, true, function (rgba) {
            expect(rgba).toEqual([0, 255, 0, 255]);
          });
          material.uniforms.image = Material.DefaultImageId;
          renderMaterial(material, true, function (rgba) {
            expect(rgba).toEqual([255, 255, 255, 255]);
          });
```

File: Specs/Scene/MaterialSpec.js [hunk 3]
```diff
@@ -655,6 +655,206 @@ describe(
...
+        expect(rgba).toEqual([255, 255, 255, 255]);
+      });
+
+      material.uniforms.image = "./Data/Images/Green.png";
+      return pollToPromise(
+        function () {
+          renderMaterial(material, true);
+          return material._textures["image"] !== material._defaultTexture;
+        },
+        { timeout: 10000 }
```
Comment (lilleyse) [inline Specs/Scene/MaterialSpec.js:718]: I don't think the timeouts are necessary. These images should be loaded well before the default timeout.

**Review by lilleyse — COMMENTED** [review]
Good start @j9liu! I confirmed that this fixes all the cases in the issue. The unit tests are solid. I just have some suggestions for how the code could be organized.

File: Source/Scene/Material.js (hunk 1 above)
Comment (lilleyse) [reply Source/Scene/Material.js:925]: Ah I see that the code in `update` was handling the destroy for this. Can it somehow be handled by `createTexture2DUpdateFunction` instead?

**Comment by lilleyse** [comment]
> Sorry about the 20+ commits; they happened when I was `git pull`-ing from `master`. If there's any way I can avoid that in the future let me know!

To fix the commit history:
* Create a branch off master
* Cherry-pick the commits you want to keep
* Force push to `unset-material-image` ([instructions for that](https://stackoverflow.com/questions/36927956/how-to-do-a-forced-push-to-another-branch-in-git))

In general if you're trying to merge `master` into your branch, use `git merge` instead of `git pull`

**Comment by j9liu** [comment]
@lilleyse - I followed your comments, let me know if anything needs changing!

File: Source/Scene/Material.js [hunk 4]
```diff
@@ -853,13 +854,29 @@ function createTexture2DUpdateFunction(uniformId) {
...
       if (!defined(material._defaultTexture)) {
         material._defaultTexture = context.defaultTexture;
       }
-      texture = material._textures[uniformId] = material._defaultTexture;
-
+      if (uniformValueIsDefaultImage) {
+        texture = material._textures[uniformId] = context.defaultTexture;
+      } else {
+        texture = material._textures[uniformId] = material._defaultTexture;
+      }
```
Comment (lilleyse) [inline Source/Scene/Material.js:879]: Since `material._defaultTexture` is set to `context.defaultTexture` above I don't think this if/else is needed. The previous code can be used.

```
texture = material._textures[uniformId] = material._defaultTexture;
```

File: Source/Scene/Material.js [hunk 5]
```diff
@@ -853,13 +854,29 @@ function createTexture2DUpdateFunction(uniformId) {
       return;
     }
 
+    if (uniformChanged && defined(texture)) {
+      if (
+        texture !== this.defaultTexture &&
+        texture !== context.defaultTexture
```
Comment (lilleyse) [inline Source/Scene/Material.js:860]: `this.defaultTexture` - is this supposed to be `material._defaultTexture`?

Can `texture !== context.defaultTexture` be removed since it's the same thing?

Maybe `material._defaultTexture = context.defaultTexture` can be set as one of the first lines in `Material.prototype.update`. I'm starting to lose track of when `_defaultTexture` is set and when it's not set. Really this is a problem with the existing code but it's worth cleaning up.

File: Source/Scene/Material.js [hunk 6]
```diff
@@ -853,13 +854,29 @@ function createTexture2DUpdateFunction(uniformId) {
...
+      ) {
+        texture.destroy();
```
Comment (lilleyse) [inline Source/Scene/Material.js:862]: I'm noticing a momentary blip where the old texture is no longer used and the new texture is still loading in. Previously the swap was smooth. Is this fixable?

File: Source/Scene/Material.js [hunk 7]
```diff
@@ -895,12 +912,18 @@ function createTexture2DUpdateFunction(uniformId) {
...
 
-        when(promise, function (image) {
-          material._loadedImages.push({
-            id: uniformId,
-            image: image,
-          });
-        });
+        when(
+          promise,
+          function (image) {
```
Comment (lilleyse) [inline Source/Scene/Material.js:917]: This code can use the newer promise syntax:

```
        promise.then(function(image) {
          material._loadedImages.push({
            id: uniformId,
            image: image,
          });
        }).otherwise(function() {
          material._textures[uniformId] = material._defaultTexture;
        });        
```

File: Source/Scene/Material.js (hunk 6 above)
Comment (j9liu) [reply Source/Scene/Material.js:862]: I tried to take care of that by moving the `destroy()` call to the `prototype.update` function -- it would only `destroy` once the new texture was transferred from the `loadedImages` array. I'm not sure how to fix this in the scope of this update function because the new texture is handled by `prototype.update`, not this one?

Comment (lilleyse) [reply Source/Scene/Material.js:863]: I see. I was thinking about an alternative like destroying the texture in the `.otherwise` callback, but that's not right either because creation/destruction of WebGL resources should happen in the render loop.

Maybe go back to how you originally had it but add a comment explaining why the code is there.

**Comment by j9liu** [comment]
@lilleyse - how does this look now?

File: Source/Scene/Material.js [hunk 8]
```diff
@@ -422,12 +422,15 @@ Material.prototype.isTranslucent = function () {
  * @private
  */
 Material.prototype.update = function (context) {
+  if (!defined(this._defaultTexture)) {
+    this._defaultTexture = context.defaultTexture;
+  }
```
Comment (lilleyse) [inline Source/Scene/Material.js:427]: I think just `this._defaultTexture = context.defaultTexture` is fine.

File: Source/Scene/Material.js [hunk 9]
```diff
@@ -895,12 +915,16 @@ function createTexture2DUpdateFunction(uniformId) {
...
-            image: image,
+        promise
+          .then(function (image) {
+            material._loadedImages.push({
+              id: uniformId,
+              image: image,
+            });
+          })
+          .otherwise(function () {
+            material._textures[uniformId] = material._defaultTexture;
```
Comment (lilleyse) [inline Source/Scene/Material.js:926]: The last thing I noticed is that the texture isn't destroyed if it goes from "Cesium_Logo_Color.jpg" to "does_not_exist".

This is a bit hard to fix given the way the material code is currently arranged. The best approach is probably to destroy the existing texture in here, even though it happens outside the render loop.

The material code is due for a refactor but that's outside the scope of this PR.

**Review by lilleyse — COMMENTED** [review]
Really close now. The code comments are very helpful. Just one last comment about destroying the texture in one case.

**Comment by lilleyse** [comment]
Thanks @j9liu!
