### PR TITLE
Made documentation fixes so that there are no false globals from JSDoc

### LINKED ISSUE #8743: Random/incorrect JSDoc
Go to: https://cesium.com/docs/cesiumjs-ref-doc/global.html or locally at http://localhost:8080/Build/Documentation/global.html

There is a hodgepodge of items that JSDoc thinks we've documented as being in the global namespace that are incorrect.  It's probably due to missing `@private` annotations or otherwise has incorrect JSDoc.

### PR DESCRIPTION
**Pull request by YoussefV**
fixes #8743

### CODE REVIEW

**Comment by cesium-concierge** [comment]
Thanks for the pull request @YoussefV!
* :heavy_check_mark: Signed CLA found.
* :grey_question: [CHANGES.md](https://github.com/CesiumGS/cesium/blob/fixed-globals-docpage/CHANGES.md) was not updated.
    * If this change updates the public API in any way, please add a bullet point to `CHANGES.md`.
* :grey_question: Unit tests were not updated.
    * Make sure you've [updated tests](https://github.com/CesiumGS/cesium/tree/master/Documentation/Contributors/TestingGuide) to reflect your changes, added tests for any new code, and ran the code coverage tool.

Reviewers, don't forget to make sure that:

- [ ] Cesium Viewer works.
- [ ] Works in 2D/CV.
- [ ] Works (or fails gracefully) in IE11.

File: Source/Scene/JobScheduler.js [hunk 1]
```diff
@@ -3,6 +3,11 @@ import DeveloperError from "../Core/DeveloperError.js";
 import getTimestamp from "../Core/getTimestamp.js";
 import JobType from "./JobType.js";
 
+/**
+ *
+ * @private
+ * @constructor
```
Comment (emackey) [inline Source/Scene/JobScheduler.js:9]: I don't think this `@constructor` was intentional.

Comment (YoussefV) [reply Source/Scene/JobScheduler.js:9]: It was added there so that JSDoc doesn't mark it as a global member. @lilleyse and I found that adding `@constructor` was needed because the `@private` isn't inherited

**Comment by lilleyse** [comment]
Looks great @YoussefV
