### PR TITLE
Fixed Matrix Multiplication Shaders

### LINKED ISSUE #4250: Check matrix multiplication in shaders
Prevent possible precision errors when transforming vertices be multiple matrices.

Go through all of the shaders and change things like:

```
vec4 positionWC = czm_inverseView * positionEC;
vec4 positionMC = czm_inverseModel * positionWC;
```

to
`vec4 positionMC = czm_inverseModelView * positionEC;`

The only exception here is the projection matrix where we would want to do the opposite. Change
`gl_Position = czm_modelViewProjection * position;`
to

```
vec4 positionEC = czm_modelView * position;
gl_Position = czm_projection * positionEC;
```

For the first change see [Creating Vast Game Worls](http://www.humus.name/Articles/Persson_CreatingVastGameWorlds.pdf) by Emil Persson.
For the second change see [Tightening the Precision of Perspective Rendering](http://www.geometry.caltech.edu/pubs/UD12.pdf) by Paul Upchurch and Mathieu Desbrun and [Depth Precision Visualized](http://www.reedbeta.com/blog/2015/07/03/depth-precision-visualized/) by Nathan Reed.

### PR DESCRIPTION
**Pull request by GGajanan1**
# Description

Fixed Matrix Multiplication in shaders
fixes #4250 

## Testing plan

# Author checklist

- [x] I have submitted a Contributor License Agreement
- [x] I have added my name to `CONTRIBUTORS.md`
- [ ] I have updated `CHANGES.md` with a short summary of my change
- [x] I have added or updated unit tests to ensure consistent code coverage
- [x] I have updated the inline documentation, and included code examples where relevant
- [x] I have performed a self-review of my code

### CODE REVIEW

**Comment by GGajanan1** [comment]
> Thank you for the pull request, @GGajanan1! Welcome to the Cesium community!
> 
> In order for us to review your PR, please complete the following steps:
> 
> * [X]  Send in a [Contributor License Agreement](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) (CLA)
> * [ ]  Add yourself to the [contributors](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTORS.md) file
> 
> Review [Pull Request Guidelines](https://github.com/CesiumGS/cesium/blob/main/CONTRIBUTING.md#pull-request-guidelines) to make sure your PR gets accepted quickly.

**Comment by ggetz** [comment]
Thanks @GGajanan1! I can confirm we have a CLA on file for you now.

**Review by ggetz — COMMENTED** [review]
Thanks for the changes so far @GGajanan1!

I think there are a few other places where this update is needed as well:
- `DepthPlaneVS.glsl`
- `EllipsoidVS.glsl`
- `GlobeVS.glsl`
- `modelToWindowCoordinates.glsl`

**Comment by GGajanan1** [comment]
@ggetz  Thanks , I have did the changes in the following PR:https://github.com/CesiumGS/cesium/pull/12367

**Comment by ggetz** [comment]
Thanks @GGajanan1! 

* Is it possible to bring your changes from https://github.com/CesiumGS/cesium/pull/12349 into this branch as well?
* Please update `CONTRIBUTORS.md` to include your username

**Comment by GGajanan1** [comment]
@ggetz  I have merged the changes from #12367  in this current branch.

**Comment by GGajanan1** [comment]
Also added my name in CONTRIBUTORS.md

**Comment by ggetz** [comment]
Perfect, thanks @GGajanan1! 

We typically don't assign issues except for our own internal issue on the Cesium team.

File: packages/engine/Specs/Scene/MultifrustumSpec.js [hunk 1]
```diff
@@ -237,7 +237,7 @@ describe(
           vs += "in vec4 position;";
           vs += "void main()";
           vs += "{";
-          vs += "    gl_Position = czm_modelViewProjection * position;";
+          vs += "    vec4 positionEC = czm_modelView * positiong; l_Position = czm_projection * positionEC;";
```
Comment (jjhembd) [inline packages/engine/Specs/Scene/MultifrustumSpec.js:240]: There is a typo here: this line should be split across 2 lines.

We generally want to use [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) instead of string concatenation. See https://github.com/CesiumGS/cesium/pull/10067. This typo is a good example of why: manually adding up strings is hard to read and easy to make a small mistake.

Can you update this section to use a template literal?

**Review by jjhembd — CHANGES_REQUESTED** [review]
@GGajanan1 thanks a lot for this work! 
I'm still testing on my end to verify the rendering result. Meanwhile, I have one comment about a typo in `MultifrustumSpec` below.

**Comment by GGajanan1** [comment]
I have added the changes

File: packages/engine/Source/Shaders/Builtin/Functions/modelToWindowCoordinates.glsl [hunk 2]
```diff
@@ -30,7 +30,8 @@
  */
 vec4 czm_modelToWindowCoordinates(vec4 position)
 {
-    vec4 q = czm_modelViewProjection * position;                // clip coordinates
+    vec4 positionEC = czm_modelView * position;
+    q = czm_projection * positionEC;
```
Comment (jjhembd) [inline packages/engine/Source/Shaders/Builtin/Functions/modelToWindowCoordinates.glsl:34]: `q` was not declared. The first use of it should include the type: 
```glsl
vec4 q = ...
```

File: packages/engine/Source/Shaders/DepthPlaneVS.glsl [hunk 3]
```diff
@@ -5,6 +5,8 @@ out vec4 positionEC;
 void main()
 {
     positionEC = czm_modelView * position;
+    vec4 positionEC = czm_modelView * position;
+    gl_Position = czm_projection * positionEC;
```
Comment (jjhembd) [inline packages/engine/Source/Shaders/DepthPlaneVS.glsl:9]: I don't think we need this change. Now we are redeclaring `positionEC`, and defining `gl_Position` twice.

File: packages/engine/Source/Shaders/EllipsoidVS.glsl [hunk 4]
```diff
@@ -13,8 +13,8 @@ void main()
     vec4 p = vec4(u_radii * position, 1.0);
 
     v_positionEC = (czm_modelView * p).xyz;     // position in eye coordinates
-    gl_Position = czm_modelViewProjection * p;  // position in clip coordinates
-
+    vec4 positionEC = czm_modelView * position;
```
Comment (jjhembd) [inline packages/engine/Source/Shaders/EllipsoidVS.glsl:16]: This change is now multiplying by `czm_modelView` twice, which will affect performance. We could do the multiplication once, then re-use the result for the `vec3` variable.
```glsl
vec4 pEC = czm_modelView * p;
v_positionEC = pEC.xyz;
```

File: packages/engine/Source/Shaders/EllipsoidVS.glsl [hunk 5]
```diff
@@ -13,8 +13,8 @@ void main()
...
+    gl_Position = czm_projection * positionEC;
```
Comment (jjhembd) [inline packages/engine/Source/Shaders/EllipsoidVS.glsl:17]: `positionEC` is not the same as `p`, so this is changing the result.

With the change from the previous comment, this line could be:
```glsl
gl_Position = czm_projection * pEC;
```

File: packages/engine/Source/Shaders/GlobeVS.glsl [hunk 6]
```diff
@@ -114,7 +114,8 @@ vec4 getPositionMorphingMode(vec3 position, float height, vec2 textureCoordinate
     float yPositionFraction = get2DYPositionFraction(textureCoordinates);
     vec4 position2DWC = vec4(height, mix(u_tileRectangle.st, u_tileRectangle.pq, vec2(textureCoordinates.x, yPositionFraction)), 1.0);
     vec4 morphPosition = czm_columbusViewMorph(position2DWC, vec4(position3DWC, 1.0), czm_morphTime);
-    return czm_modelViewProjection * morphPosition;
+    vec4 positionEC = czm_modelView * position;
```
Comment (jjhembd) [inline packages/engine/Source/Shaders/GlobeVS.glsl:117]: This is significantly changing the output. For a consistent result, this could be:
```glsl
vec4 positionEC = czm_modelView * morphPosition;
```

However, we may want to avoid using the `positionEC` name for modified positions, because that name has a very specific meaning in most of the rest of the code.

File: packages/engine/Specs/Scene/MultifrustumSpec.js [hunk 7]
```diff
@@ -237,7 +237,11 @@ describe(
           vs += "in vec4 position;";
           vs += "void main()";
           vs += "{";
-          vs += "    gl_Position = czm_modelViewProjection * position;";
+          vs = `
+              gl_Position = czm_modelViewProjection * position;
```
Comment (jjhembd) [inline packages/engine/Specs/Scene/MultifrustumSpec.js:241]: I think this is a copy-pasting error. `gl_Position` is now defined twice.

**Review by jjhembd — CHANGES_REQUESTED** [review]
Hi @GGajanan1, thanks for the update!
I looked through a little more closely, and noticed a few things in the code. Once these are fixed, I can run the rendering tests to confirm.

**Review by jjhembd — APPROVED** [review]
@GGajanan1 I pushed a commit implementing my commits. This should be ready to go once we add a note to CHANGES.md
